### ISSUE TITLE
Queuing Jobs

### ISSUE THREAD

**Issue by qoomon** [rundeck/rundeck#1047]
I'd like to have the Option to queue jobs if the are not allowed to run in parallel

**Comment by kolistivra** [comment]
This would be a great enhancement, indeed!

**Comment by LukeAsh** [comment]
Are there any plans to include this in upcoming releases?

**Comment by jamesweakley** [comment]
This feature would be spectacular

**Comment by blairpaine** [comment]
+1

**Comment by corpx** [comment]
+1 as well.

**Comment by gregwjacobs** [comment]
+1

**Comment by corpx** [comment]
So I wrote a rundeck job to push a job into a rabbitmq queue.

And I have a job running in a screen that picks up from the queue and runs it in order, so it doesnt step over each other.   Not the most ideal way, but its working fine for now.

**Comment by steveblackmon** [comment]
+1

**Comment by metacoma** [comment]
+1

**Comment by coferc** [comment]
+1

**Comment by ARentz07** [comment]
This would be tremendously useful, 👍

**Comment by rasebo** [comment]
+1

**Comment by Theaxiom** [comment]
+1

**Comment by rguiliani** [comment]
+1

**Comment by Miminoux** [comment]
+1

**Comment by samber** [comment]
+1

**Comment by natlibfi-arlehiko** [comment]
+1

**Comment by radius314** [comment]
+1

**Comment by puremourning** [comment]
This would be useful for us using rundeck as part of a CI pipeline.

Here's the use-case (sorry I can't access trello from here >_<):
 - user submits a review-request (e.g. gitlab pull request, reviewboard review)
 - gitlab-ci or jenkins builds the code
 - gitlab-ci or jenkins calls the rundeck API for a "Deploy and Integration Test" job with the build location, etc. as parameters
 - the "Deploy and Integration Test" job does not allow multiple executions, as there is only one test farm
 - "Deploy and Integration Test" deploys the build to the test farm
 - "Deploy and Integration Test" runs the integration tests on the test farm

The point is that there is a single rundeck job and a single test farm. We would like the CI systems to be able to trigger the job via API and sit around polling for rundeck's "Deploy and Integration Test" job to complete. We have this working, but currently race causes one of the two to just fail.

Both gitlab-ci and jenkins have job queuing, but they are (obviously) independent, so a downstream solution would be ideal. I would hate to have to create yet-another-build-system or otherwise to resolve.

At the risk of embarrassingly oversimplifying the problem, I guess the obvious approach would be for the completion of an execution to trigger then next queued execution for that job (sorted by submission time) - a bit like timed ("run later") executions, but the trigger being the completion of an execution for a specific job.

**Comment by kosii** [comment]
:+1:

**Comment by guzmanbraso** [comment]
+1

**Comment by eedduuar** [comment]
+1

**Comment by Tombar** [comment]
+1

**Comment by gargrag** [comment]
+1

**Comment by gschueler** [comment]
Adding to trello board, please vote there; https://trello.com/c/MijkQiFP

**Comment by Theaxiom** [comment]
Why are we even voting on this? Please, this is a must for an orchestration platform. I've been using Rundeck for years now and bringing it to every new place I work with me and this is consistently an issue. I have people that won't use Rundeck in place of Jenkins for orchestration because of this very issue. I firmly believe that this issue is lowering adoption rates of Rundeck.

**Comment by ahonor** [comment]
@Thexiom, I believe there may be a configurable solution. There may be an existing ThreadPool Factory impl that already does this and if so it would simply require modifying the quartz config properties file. It's probably just a research effort to change the class name.

**Comment by sinksc** [comment]
I want to make sure I am understanding this issue request because I was about to open one that might be a dup of this one.

If I have 10 separate ad-hoc jobs in RD, I want to be able to run a serial batch of jobs. For example, run jobs #3, then 4, then 5, then 6 in a single run without having to manually initiate each job when its predecessor is finished. I know that you can create a single job that has other jobs as sub-steps, but I want to be able to queue them up on an ad-hoc basis if needed.

If that's the same as what this issue is asking, then consider me a +1!

**Comment by roman-io** [comment]
+1

**Comment by gufertum** [comment]
+1

**Comment by Theaxiom** [comment]
How is this basic functionality still missing from Rundeck?!!! Rundeck is amazing, but IMHO this is a no-brainer feature and should be a top priority!

**Comment by joelsdc** [comment]
+1

**Comment by joelsdc** [comment]
I'm surprised trello board only has 20 votes.. https://trello.com/c/MijkQiFP

**Comment by Axiioss** [comment]
+1

**Comment by wggit** [comment]
+1

**Comment by Theaxiom** [comment]
Voting anywhere has no effect in regards to this feature.

**Comment by lightarrow** [comment]
yeah implementing a separate database for this takes time.

**Comment by Theaxiom** [comment]
It's called a message queue... while I do appreciate Rundeck and all of the work that has gone into it, not to mention the individuals who have poured their heart and souls into it; I must say that this feature is relatively trivial and would bring a lot of value to the product. In it's current form, we are required to have a standalone MQ server setup separately and another process (CRON script) which is monitoring job status in Rundeck every minute via API which kicks the next job off if the current status of the project is not running. This does work for us in the meantime, but it is a lot of overhead for us to maintain when such a basic feature for a orchestration tool to have a queue is missing. I don't understand why after so many years Rundeck does not yet have this functionality.

**Comment by lightarrow** [comment]
I am using api calls to manage remote batch and update a scheduling database for exceptions to cron. 

, Ron

**Comment by lukasged** [comment]
This is really a required feature for a complete orchestration tool. Hoping to see it arrive to Rundeck.

**Comment by Theaxiom** [comment]
5 years later after being initially reported, this may be the slow death of Rundeck. It's unfortunate because I really love Rundeck and advocate for it as much as possible.

**Comment by Yellender222** [comment]
Really helpful this feature

**Comment by lightarrow** [comment]
Im now managing my own FIFO queue and it has added great functionality to job management.

**Comment by Theaxiom** [comment]
@lightarrow please share your implementation details, if you will, so others can benefit from your knowledge and experience! Thank you! :)

**Comment by lightarrow** [comment]
I don’t think I have the liberty to disclose that information. Its custom and uses inline scripts to manage the queue. 
Most languages have a queueing class. Calls and implementation are described in the standard library. Search your language plus FIFO and you can see an implementation.

**Comment by moskvin** [comment]
+1

**Comment by Theaxiom** [comment]
@lightarrow I wasn't asking for my benefit, I have previously built message bus/queue systems and integrated third-party systems such as RabbitMQ into applications, etc. I was asking for the benefit of others. I could not get traction at my organization for Rundeck because of some fundamental issues as well as licensing, so we are no longer using or promoting Rundeck internally.

As far as your implementation, I can't see how providing high-level implementation details would violate any sort of IP, unless you are using a proprietary queueing system or other integrations which were built internally or have some sort of licensing agreement attached to it which prohibits public discussion. I understand that you may work at an organization which believes it owns everything that it "Creates" and that you are bound to agreements which enforce certain behaviors; however, I am fairly confident that the implementation which you have described is pretty novel and would not be patentable, nor would it be considered IP in any form, especially if you are using open-source projects. I could be wrong, but something tells me that there is no problem with you explaining the basic integration to those who would not necessarily have the acumen or experience that you or I have to be able to implement such a system from scratch.

The problem is, most people don't have the sharing mentality due to the society which has conditioned us to fear, greed, self-centeredness and so-on; so I can unfortunately understand if you don't want to share the high-level implementation details of your specific system integration. That is after all your prerogative and nobody is denying you that. I just call attention to such anti-human behavior when I get the chance in order to promote self-awareness; not trying to shame you but simply hoping I can inspire you to break out of your programmed auto-pilot and start making conscious decisions for yourself.

- Namaste <3

**Comment by lightarrow** [comment]
I will publish when I have approval. 


Sharing knowledge is the most fundamental act of friendship. Because it is a way you can give something without loosing something.

Richard Stallman

**Comment by Theaxiom** [comment]
Thank you @lightarrow <3

**Comment by lightarrow** [comment]
So the easy way is to use a cloud resource say SQSqueue FIFO. Then process the messages that are generated by cloudwatch events. Utilizing the metadata around the event, and the file itself to determine if jobs are running. SQSqueue has a time out value so you can process a message and just leave it on the queue and the next few reads will not see it. Its not until your conditions are met that you run a job.

**Comment by Theaxiom** [comment]
@lightarrow you are awesome. :)

**Comment by charlescanato** [comment]
Rundeck should work for me as a fool test. This is the 3rd time I get team adherence to it, just to, after a few weeks, have to reply to someone "ahhh no, Rundeck will only refuse a job or process them all at the same time, ok I'll do a queuing script for the nth time." Argh. I blame this on ME forgetting that Rundeck does not have this feature, not on Rundeck - after all they never have promised this (yes, although I also think it's a truly basic feature for what it does).

**Comment by cdaf** [comment]
A rudimentary solution I've used for this challenge is to have a parent job which calls the RD CLI in a loop, with the --follow parameter to follow the job to completion, then execute the next one, resulting log ...

rd.bat run --follow -p 'Certificates' -j 'apply-cert' -- -MACHINE 'server-1.local' -SERVER 'iis'
rd.bat run --follow -p 'Certificates' -j 'apply-cert' -- -MACHINE 'server-2.local' -SERVER 'iis'
rd.bat run --follow -p 'Certificates' -j 'apply-cert' -- -MACHINE 'server-3.local' -SERVER 'rdg'

**Comment by giuseppeborgese** [comment]
This issue was open in 2014 and last comment is January 2021, I don't know if you notice BUT now there is the queue option in the enterprise version https://docs.rundeck.com/docs/manual/jobs/job-queue.html#enabling-the-queue-for-a-job
So it is kind of revolved if you have the Rundeck enterprise.

**Comment by fdevans** [comment]
Thank you @giuseppeborgese 
You're correct, this is a available in Enterprise.
