### ISSUE TITLE
Inline scripts for jobs do not honor File Copy Settings

### ISSUE THREAD

**Issue by mbidewell** [rundeck/rundeck#1056]
When rundeck uploads a script created as a job step, Rundeck ignores the file copy settings on the project and uploads to /tmp or the value of the "file-copy-destination-dir" property.  This will cause if the project expected destination differs from the default remote values.

**Comment by ahonor** [comment]
@mbidewell Also, what version of Rundeck?

**Comment by mbidewell** [comment]
This was on 2.3.2 release.  The configuration "Remote Filepath" if set for a "script copier" file copy is ignored for executions.

Does that help?

**Comment by gschueler** [comment]
the "Remote Filepath" for script copier should be removed, it is now not going to be used.  The reason for this is that file copiers will always be provided with the remote destination path.  For Script steps in jobs, the path will be generated, and for "File Copy" steps in jobs, the path is specified by the user.

The problem is there is no framework or project level setting to customize the destination path, only the default and the node-level setting.

To wit: we need to add framework and project level setting for destination file copy path. I propose these:

`framework.file-copy-destination-dir` and `project.file-copy-destination-dir`

This will allow the project setting to be used (for all file copiers, not just script execution)
