### ISSUE TITLE
Add job option to have nodes default to un-checked

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#114]
It would be useful to have a job option that causes the dispatch nodes to be unchecked by default, such that the job executor must enable the desired hosts at job runtime.  This would allow node selection at runtime, without the risk of the job executor accidentally executing on all nodes defined in the job.

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/470)

Original Creator: Andrew Crawford

**Comment by jasonhensler** [comment]
+1.

**Comment by gschueler** [comment]
trello card: https://trello.com/c/01DpT2jR

**Comment by richiereynolds** [comment]
I can't get that trello link to work I'm afraid. Any ETA on this?

**Comment by gschueler** [comment]
does this work: https://trello.com/c/01DpT2jR

**Comment by dave-knight** [comment]
+1

**Comment by richiereynolds** [comment]
Yes, that link works, thanks.
Is the scope creep into all sort of clever ideas here stopping what would be a very useful, very simple, feature being implemented? Simply having no nodes checked by default instead of all nodes, sounds like a far safer and more sensible default to me for all jobs. If not the default then a simple option on job creation to say "no nodes selected" for this job would be fine too.

**Comment by gschueler** [comment]
@richiereynolds no, this issue is just backlogged, sorry :(  Another related request is to disable the ability to change the target nodes at all, so in the end these two changes might be combined.  The other ideas in that trello card are not a high priority

**Comment by richiereynolds** [comment]
Thanks!

**Comment by smags** [comment]
+1
