### ISSUE TITLE
Feature Request: redirect to 'Log Output' tab after submitting a job instead of summary tab

### ISSUE THREAD

**Issue by TomGudman** [rundeck/rundeck#1144]
Hi, 

It would be very useful to have the possibility to immediately see the output of the job we have just triggered instead of displaying the default 'Summary' tab. 

The majority of our jobs are tasks we outsource to end users to be able to trigger operations themselves that returns useful information (e,g: credentials, list of connections, etc) they need straight away. Clicking on the 'Log output' tab is an extra step that could be removed to simplify the end user (our) workflow. 

This parameter could be global or per project or maybe even per job. I dunno from the code point of view how this can be managed though. Sorry I am not very fluent in Java

Version: 2.4.2
OS: Centos6

**Comment by badarahmed** [comment]
+1

**Comment by jedblack** [comment]
+1

**Comment by gschueler** [comment]
a previous request to use `#output` URL fragment on the executio page to automatically select the output tab would I think be necessary, and then augment/change the behavior of the "follow output" checkbox when running a job

**Comment by gschueler** [comment]
this previous request #1107

**Comment by ahonor** [comment]
+1

**Comment by TomGudman** [comment]
Is it possible to add that one in the 2.6.0 milestone? 
I think that could be handy for everybody especially when I see #1154

Thanks

**Comment by dcorneli** [comment]
+1

**Comment by TomGudman** [comment]
What's missing or hard to code/change to make this happen ? Maybe some extra details could help others to code it.

**Comment by ahonor** [comment]
I think there are two ideas here:

1. job definition defines the default tab to follow
2. run page lets a job runner choose the tab

**Comment by dcorneli** [comment]
+1

**Comment by dirkniblick** [comment]
+1 - Adding this feature would be such a game changer.  It's hella annoying to try to flip backwards in the executions of a job trying to find the one that "failed" but didn't really *fail*.  I tried to find a way to get execution output from the rd-cli, but that doesn't seem to be an option.

**Comment by 0xAalaoui** [comment]
+1

**Comment by gschueler** [comment]
@dirkniblick you can use `rd` to get the output, with `rd executions follow --restart -e $ID`

**Comment by dirkniblick** [comment]
@gschueler, I may not have described the problem correctly.  I'm not looking to follow a particular job.

Say you have a job which runs a script often (e.g., every minute or two).  The script does something wrong - something transient - but it doesn't bomb out and throw a non-zero exit code.  You find out later the script does something wrong, but you don't know when exactly.  You might add some verbosity to the script and it fails again.  At that point, I want to flip through the executions and locate the problem output.  After opening an execution, I gotta click "Log Output", "Previous", "Log Output", "Previous", etc.  It might seem silly to complain, but it's tedious moving the mouse back and forth, even if you just want to flip through the output of jobs to see how they run differently over time or whatnot.

I think a lot of your users would agree that the Log Output tab needs some love, because I know that's usually the one I want to see most/first.  :^)  There's #1867 and #1154  plus it would be helpful if the #output anchor referenced by ${execution.href} (included in my email notifications) actually opened that tab (not sure if there's already a request for that).

**Comment by gschueler** [comment]
@dirkniblick I understand, I was just pointing out the ability to use cli to get output (in case you had not discovered that).  Having the log output show by default is a useful feature to add, we want to do it, (I know it seems such a small change too). Sorry, can only say it will happen as soon as there's time to do it!

**Comment by 2ZZ** [comment]
+1 would be useful
