### ISSUE TITLE
Limiting execution output through API with lastlines seems to be off by 2

### ISSUE THREAD

**Issue by harlanbarnes** [rundeck/rundeck#1207]
Hi there! First off, thanks for all the wonderful work you do on this project. I am a happy rundeck user and want to make sure you know it's appreciated.

I'm working on the `lita-rundeck` handler for the Lita chatbot and was adding the ability to show the last X lines of an execution on request.

Here's the output of my test job with no limit on the output ... (the script just prints a counter and the timestamp)

```
curl -H "X-Rundeck-Auth-Token: notasecret" -k "https://rundeck.mycompany.com/api/5/execution/6858/output?format=text"

1 Thu Apr 30 23:16:30 UTC 2015
2 Thu Apr 30 23:16:31 UTC 2015
3 Thu Apr 30 23:16:32 UTC 2015
4 Thu Apr 30 23:16:33 UTC 2015
5 Thu Apr 30 23:16:34 UTC 2015
6 Thu Apr 30 23:16:35 UTC 2015
7 Thu Apr 30 23:16:36 UTC 2015
8 Thu Apr 30 23:16:37 UTC 2015
9 Thu Apr 30 23:16:38 UTC 2015
10 Thu Apr 30 23:16:39 UTC 2015
```

When I add the `lastlines` URL parameter with a value of 5, I only get 3 lines:

```
curl -H "X-Rundeck-Auth-Token: notasecret" -k "https://rundeck.mycompany.com/api/5/execution/6858/output?format=text&lastlines=5"

8 Thu Apr 30 23:16:37 UTC 2015
9 Thu Apr 30 23:16:38 UTC 2015
10 Thu Apr 30 23:16:39 UTC 2015
```

I tested a bunch of variations and they are consistently off by 2, so I can obviously work around it in my code, but I just thought it was weird and figured I was doing something wrong that wasn't immediately obvious to me.

BTW, I've tested on both an oldish (2.0.4) and new (2.5.0) and they both gave me the same results.

Thanks for your time!

**Comment by gschueler** [comment]
Thanks for the report. I looked into this and the cause seems to be that our log format used to only record actual execution output (log messages), but it now records additional metadata as log entries which don't contain actual log messages.  But the logic to look for a particular number of *log message* lines was not updated, so it's just seeking to the wrong position when "lastlines" is specified, causing it to be offset by some number of entries, in your case it happened to be 2.
