### ISSUE TITLE
Command argument with embedded quoted string does not work

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#1291]
command:

```
/opt/jboss/jboss-eap-6.2/bin/jboss-cli.sh -c --command="deploy /opt/deploy/${option.warversion}"
```

The `--command` portion is not passed to the shell correctly.  Attempting to quote it produces an error `'"deploy' is not a valid operation name.`.

```
/opt/jboss/jboss-eap-6.2/bin/jboss-cli.sh -c '--command="deploy /opt/deploy/${option.warversion}"'
```

**Comment by gschueler** [comment]
A workaround is to use an inline-script and allow Bash to perform the argument parsing as expected:

~~~ {.bash}
#!/bin/bash
/opt/jboss/jboss-eap-6.2/bin/jboss-cli.sh -c --command="deploy /opt/deploy/@option.warversion@"
~~~

**Comment by gschueler** [comment]
ref #602

**Comment by subhasis12** [comment]
WFLYCTL0449: Operation start against the resource at address /host={host}/server-config={server-config-value} is deprecated.
I am trying to use the command as below
${JBOSS_HOME}/bin/jboss-cli.sh --connect "/host=${host}/server-config=${serverConfig}:start"

can someone help as there is no proper document available for this.

**Comment by fdevans** [comment]
We apologize if this issue was missed.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
