### ISSUE TITLE
How to configure ssh for tty

### ISSUE THREAD

**Issue by n2studio** [rundeck/rundeck#1303]
Whenever I have a sudo command in my scripts, I get the error "sorry, you must have a tty to run sudo". I don't want to remove the "requiretty" from the sudoers file from my machines for security reasons. 

How do I configure rundeck globally (in framework.properties) so that anytime I run a script, it will pass the -t argument to the ssh command and execute scripts with a tty?

**Comment by jmkoch99** [comment]
I have the same requirements, and do not want to remove requiretty.  Due to OS security restrictions, a workaround I found was to have the entire script step invoked with sudo, rather than a line within the script.  I understand this introduces other security risks because the whole script is ran as root, but for my usecase, this was acceptable.

This was completed by changing the step advanced options "Invocation String" to "sudo ${scriptfile}". This would allow the script to be invoked on the server by the user specified for the node, but to run as root.  If there were parts of the script that should not be ran as root, I modified  those commands (within the script) to run as a specific user (i.e. sudo -u someuser command).  I did have to manage/modify the sudo privs, but this workaround allowed me to force user authentication to the server, then have that user run "sudo runThisScript.sh"

I too would like to find out how to force the ssh command to pass -t, but in the mean time, this is how I got sudo to work.  This workaround likely will not work with many usecases, as it requires the user to have full sudo privs, or sudo privs to run any script within a specific directory, which is not ideal.

**Comment by mkeysersoze** [comment]
To whome it may concern, when configuring the Node Executor, make sure to check the "Force PTY" checkbox, this will always force the use of a new pty.

**Comment by noname34** [comment]
Have you found the solution guys?

**Comment by ahonor** [comment]
See @mkeysersoze to learn how to force pty
