### ISSUE TITLE
ERROR BootStrap: NOT importing existing filesystem projects filesystem

### ISSUE THREAD

**Issue by ssbarnea** [rundeck/rundeck#1402]
I get this error message in the logs with a new deployment of rundeck 2.5.3-1 and it seems that there is no hint regarding what this does mean and what to do to resolve it. 

The service is starting and I am able to login, still I do see this clear ERROR level in the logs an I suspect that this is a sign of another issue.

**Comment by ddzed15** [comment]
Hello,
I think that can be ignored and you can verify if Rundeck functionalities are working ( creating projects, execution of jobs etc). 

I reckon you are *not* using DB storage for projects and still using the default "File Storage". ( check your rundeck-config.properties to see if this is set: rundeck.projectsStorageType=db ). 
If not, Rundeck is just warning that it is not importing existing filesystem projects into DB. 

If you *do* enable DB storage, you will see this print below:
```bash
ERROR  error, importing existing filesystem projects
```

I think that  these should just be a WARN instead of an ERROR. perhaps.
Below is the code snippet:
```groovy
179             //import filesystem projects if using DB storage
180             if((grailsApplication.config.rundeck?.projectsStorageType?:'db') == 'db'){
181                 log.error("importing existing filesystem projects")
182                 projectManagerService.importProjectsFromProjectManager(filesystemProjectManager)
183             }else{
184                 log.error("NOT importing existing filesystem projects ${grailsApplication.config.rundeck?.projectsStorageType}")
185             }
```
Hope this helps.
Cheers, Dharmendra

**Comment by ssbarnea** [comment]
I fact my rundeck-config.properties does not have this entry at all
```
loglevel.default=INFO
rdeck.base=/var/lib/rundeck
dataSource.dbCreate = update
dataSource.url = jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true;TRACE_LEVEL_FILE=4
```
I mention that this is a new installation.

**Comment by gschueler** [comment]
it should be a info/warning level, not error level message.

you do not need the `rundeck.projectsStorageType` config, unless you want to store the project configuration in the db rather than on the filesystem.

**Comment by ahonor** [comment]
Please reopen if this remains a concern
