### ISSUE TITLE
execution flag on second file in script plugin

### ISSUE THREAD

**Issue by vvchik** [rundeck/rundeck#1421]
Hi, I trying to create my own plugin for rundeck
it should have one executor and one file copier script 
both of them have execution flag   

```
# ls -l test-plugin/contents/ 
-rwxr-xr-x 1 root root  834 Aug 26  2015 cp.rb*   
-rwxr-xr-x 1 root root 5481 Aug 26  2015 exe.rb*

```

but if you try to run some job, second command in chain is failed with access denied exception (in my case it is copying of file, but it depend that you call first)
that because second file from plugin copied into cache folder without execute flag

```
# ls -l /var/lib/rundeck/libext/cache/test-plugin/   
-rw-rw-r-- 1 rundeck rundeck  834 Aug 26 07:14 cp.rb   
-rwxrw-r-- 1 rundeck rundeck 5481 Aug 26 07:14 exe.rb*
```

**Comment by gschueler** [comment]
I think this may be caused by the plugin loader system: when two plugin (node-executor and file-copier) are defined in the same zip, it may not be correctly setting the executable flag for one of the scripts.

A workaround could be either to create two zip each containing a single plugin definition, or combine the two scripts into one, and invoke it with a different argument for each plugin

**Comment by ahonor** [comment]
Please reopen if this remains a concern
