### ISSUE TITLE
Rundeck not loading profile correctly when running "Local Command"??

### ISSUE THREAD

**Issue by snebel29** [rundeck/rundeck#1424]
Hi,
I realize that environment variables like $PATH are not available when running a "Local Command" but they are when running a "Command" over localhost

I think this is not expected, "Local Command" is a useful feature and IMHO should load the rundeck profile correctly, otherwise something you run could fail, in my case this is chef knife tool which needs $PATH available.

I'm using 2.5.2-1 version, find here a test YAML job definition

<pre lang="yaml">
<code>
- id: 391b2658-ea32-47a6-a0c4-8177fe8a230c
  project: 'test'
  loglevel: INFO
  sequence:
    keepgoing: false
    strategy: node-first
    commands:
    - exec: echo $PATH
    - type: localexec
      nodeStep: true
      configuration:
        command: echo $PATH
  description: ''
  name: test_environment
  uuid: 391b2658-ea32-47a6-a0c4-8177fe8a230c
</code>
</pre>

What do you think about?
Thanks in advance

**Comment by nfrankish** [comment]
I seem to be having the a issue that might be releated.. Namely powershell failing to add modules..

**Comment by kensel** [comment]
Hello,
I have had the same issue and found out after much debugging it is because the environment variables aren't passed through.

It appears to be an issue in [LocalExecNodeStepPlugin.java](https://github.com/rundeck/rundeck/blob/master/plugins/localexec-plugin/src/main/java/com/dtolabs/rundeck/plugin/localexec/LocalExecNodeStepPlugin.java).
I would hazard a guess it is line 128: `Map<String, String> env = DataContextUtils.generateEnvVarsFromContext(nodeData);` 
as it doesn't appear to append the existing local variables.

Also I found the easiest way to show the issue is a job running on the rundeck server with steps Command and Local Command running: `cmd /c "set"`.  You will see the Command log output containing APPDATA, PATH, and the RD_* variables but the Local Command only has COMSPEC, PATHEXT, PROMPT, SystemRoot and RD_* variables.

The workaround I have so far is to create a project global variable and have my python script copy the RD_GLOBALS_PATH environment variable to os.environ['PATH'] before continuing the rest of the script and erroring out.
