### ISSUE TITLE
Log output out of order

### ISSUE THREAD

**Issue by suprdave23** [rundeck/rundeck#1425]
When running a job that has a lot of text output, the output seems to be getting shown out of order in the "Log Output" tab. I have tried adding some sleep statements to my script and it has helped somewhat, but is still not perfect.

When running this script just in Bash, the output is of course not out of order.

How do I go about correcting this? This is with version 2.5.2-1

Thanks!

**Comment by ahonor** [comment]
@suprdave23 do you know if there is both stderr and stdout mixed in the file? Also, is this for a multi-threaded execution?

**Comment by suprdave23** [comment]
Hi Alex,

There is indeed a mix of stdout and stderr. This is not multi-threaded, just a (somewhat) simple bash script.

**Comment by ahonor** [comment]
Do the stdout messages appear in order with the stderr more randomly dispersed?

**Comment by suprdave23** [comment]
It appears stdout stays in order while stderr gets randomly dispersed.

Here is a good example. Simple bash script:

for i in `seq 1 20`
do
	echo $i

	x=$((i+20))

	echo $x >&2
done


Output from shell:

-bash-4.1$ bash test.sh 
1
21
2
22
3
23
4
24
5
25
6
26
7
27
8
28
9
29
10
30
11
31
12
32
13
33
14
34
15
35
16
36
17
37
18
38
19
39
20
40



Output from Rundeck:

13:48:27			211
13:48:27			22
13:48:27			23
13:48:27			2
13:48:27			3
13:48:27			4
13:48:27			5
13:48:27			6
13:48:27			7
13:48:27			8
13:48:27			9
13:48:27			10
13:48:27			11
13:48:27			12
13:48:27			13
13:48:27			14
13:48:27			15
13:48:27			16
13:48:27			17
13:48:27			18
13:48:27			19
13:48:27			20
13:48:27			
13:48:27			24
13:48:27			25
13:48:27			26
13:48:27			27
13:48:27			28
13:48:27			29
13:48:27			30
13:48:27			31
13:48:27			32
13:48:27			33
13:48:27			34
13:48:27			35
13:48:27			36
13:48:27			37
13:48:27			38
13:48:27			39
13:48:27			40



Output from Rundeck if I change "$x" to output to stdout instead of stderr:

13:52:31			1
13:52:31			21
13:52:31			2
13:52:31			22
13:52:31			3
13:52:31			23
13:52:31			4
13:52:31			24
13:52:31			5
13:52:31			25
13:52:31			6
13:52:31			26
13:52:31			7
13:52:31			27
13:52:31			8
13:52:31			28
13:52:31			9
13:52:31			29
13:52:31			10
13:52:31			30
13:52:31			11
13:52:31			31
13:52:31			12
13:52:31			32
13:52:31			13
13:52:31			33
13:52:31			14
13:52:31			34
13:52:31			15
13:52:31			35
13:52:31			16
13:52:31			36
13:52:31			17
13:52:31			37
13:52:31			18
13:52:31			38
13:52:31			19
13:52:31			39
13:52:31			20
13:52:31			40

**Comment by plambert** [comment]
Output is flushed on each write if writing to a terminal, but buffered if not.

For example, run your script in bash with: 

bash test.sh | cat

Even interactively, the output is different than without the pipe.

It's technically possible for Rundeck to be modified to provide an option to emulate a TTY on STDOUT in order to have libc flush writes immediately.  However, that'd greatly reduce performance for anything producing a lot of output, and especially increase the network traffic and CPU required (by reducing any compression, and sending much smaller packets).

It certainly should remain possible to set the default in a large installation to not emulate a TTY on STDOUT.

**Comment by spaced0gg** [comment]
I believe we are seeing another symptom of this issue.

We are running a Job with 3 steps:

1. Script that outputs the checksum of linux and solaris software packages we are deploying
2. Export global variable for linux checksum
3. export global variable for solaris checksum

The issue we are seeing is that the script in step 1 is executing but the output is not being flushed to the log file.  We can see with -x debug logging that stderr is showing the script fully executing, but the rdlog does not contain all the output.  (we can see the stderr indicating echo has been executed, but we are not seeing the output in the rdlog file).

This results in eiither step2 or step 3 failing with:

Empty value

We are testing with an additional step that sleeps to see if this solves the problem.

Can you confirm if the stdout not being flushed could affect the global variable creation in this way please?

**Comment by fdevans** [comment]
We apologize if this issue was missed.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
