### ISSUE TITLE
Retry Failed Nodes... fails to retry nodes in job that contain workflow steps

### ISSUE THREAD

**Issue by eduardchernomaz** [rundeck/rundeck#1433]
Hello,

Example of the setup:
- **job 1**
  - step 1 - bash script runs against server 1 and server 2
- **job 2**
  - step 2 - bash script runs against server 3 and server 4
- **job 3**
  - step 1 - job reference **job 1**
  - step 2 - job reference **job 2**

If a node in any of the steps in **job 3** fail and the user wants to retry failed nodes, **job 3** starts all over from scratch again and does not run against failed nodes only.

**Comment by ambikads** [comment]
I have a similar request. Currently the 'Retry' option in the job page retries all nodes instead of retrying only on failed nodes. We run jobs on 1000+ nodes so this feature is highly desirable. I prefer to have the retry failed nodes first, the retry failed step on a failed node is a bonus. Is this somewhere in your road map? We use Rundeck version 2.6.1 and exploring 2.10 but don't see this feature in 2.10 as well.

**Comment by brucegivens** [comment]
+1

**Comment by rdemendoza** [comment]
+1

**Comment by rdemendoza** [comment]
+1

**Comment by rdemendoza** [comment]
+1

**Comment by fdevans** [comment]
Due to the age of this request and more recent feature releases we are going to close this request.  If there are still gaps in the feature set please feel free to open an enhancement request against the current version of Rundeck with your ideas.
Thank you, 
The Rundeck Team
