### ISSUE TITLE
Default permissions for file key storage

### ISSUE THREAD

**Issue by jyaworski** [rundeck/rundeck#1521]
Hello:

When files are added to key storage with the file storage provider, the default permissions are too open and the OS refuses to load them. This is on CentOS6. Could rundeck ensure correct permissions?

```
[rundeck@rundeck1 keys]$ ls -lsa blah.key/
total 12
4 drwxrwxr-x 2 rundeck rundeck 4096 Oct 28 20:10 .
4 drwx------ 4 rundeck rundeck 4096 Oct 28 20:10 ..
4 -rw-rw-r-- 1 rundeck rundeck    8 Oct 28 20:10 blah
[rundeck@rundeck1 keys]$ ssh-agent ssh-add /var/lib/rundeck/var/storage/content/keys/blah.key/blah
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0664 for '/var/lib/rundeck/var/storage/content/keys/blah.key/blah' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
```

**Comment by scalp42** [comment]
Running into this as well, private keys need `0600` for ssh (working around by using Chef to take care of it).

**Comment by gschueler** [comment]
when using key storage, the files on disk are not intended to be used directly, you should configure rundeck to use the keys via the storage facility (using storage path).  For example, they may be encrypted

**Comment by jyaworski** [comment]
@gschueler I was using key storage.

**Comment by scalp42** [comment]
same here @gschueler

**Comment by ahonor** [comment]
When using the keystone you should not reference the physical path on the filesystem. The key data will be made available to the plugin.

**Comment by jyaworski** [comment]
This happens even using the keystore pathing from the GUI; this was just me confirming what the issue was from the CLI.

**Comment by gschueler** [comment]
@jyaworski do you mean that the file permissions created by the key storage system are preventing you from using the keys via Rundeck? Or are you saying just that Rundeck should set the file permissions to a lower level for a system security standpoint?

**Comment by jyaworski** [comment]
I mean the former. The filesystem-level permissions. Rundeck goes to access the key and ssh denies it because the permissions are too open.

**Comment by gschueler** [comment]
@jyaworski ok, i'll try to verify that.... But I don't think that if used via the Key Storage path that the permissions would be an issue.  Basically Rundeck provides the private key data directly to Jsch, instead of telling it a file path; so file permissions shouldn't even crop up.  For example, you can configure the Key Storage to store in the database, and Rundeck uses it the same way. I'd think the only way to have that error is if using the file path directly to rundeck (`ssh-keypath="/var/lib/rundeck/..."`) instead of the Key Storage Path (`ssh-key-storage-path="keys/blah.key/blah"`).  But I will definitely try to reproduce this issue.

Do you use the key storage path configured per-node, or is it configured at the project level?  I'm wondering if perhaps there is still a configuration causing a file path to be used.

**Comment by scalp42** [comment]
@gschueler if you use the script-exec trick and use ssh directly, you'll run into the issue (right now we're using Chef to fix it for us).

**Comment by bdwyertech** [comment]
You guys could probably leverage a cron that does this...
```
chown -R rundeck:rundeck /var/lib/rundeck/var/storage/content && find /var/lib/rundeck/var/storage/content -type f \! -perm 600 -exec chmod 0600 "{}" \;
```
