### ISSUE TITLE
Workflow with Node-oriented Strategy does not work as described

### ISSUE THREAD

**Issue by rophy** [rundeck/rundeck#1527]
rundeck version: 2.6.1-0-SNAPSHOT

How Node-oriented Strategy is expected to work:
![image](https://cloud.githubusercontent.com/assets/592046/10881054/af5c84d0-819a-11e5-9afd-586dafd37524.png)

With 4 nodes, given a job workflow like this:
![image](https://cloud.githubusercontent.com/assets/592046/10881265/4f402ece-819c-11e5-92cc-dbdd13946215.png)

I would expect each node doing 3 steps on their own.

Actual result: from the screenshot below you can see that 

- First 3 nodes have completed Step 1
- In order to perform Step 2, 3 nodes are waiting for CRTVM0024 to complete its step 1, which looks like the job is using "Step-oriented Strategy".

![image](https://cloud.githubusercontent.com/assets/592046/10881183/abe95db8-819b-11e5-90ca-498a82a9077d.png)

**Comment by gschueler** [comment]
a Job reference can be either a Node step, or a Workflow step.  

Rundeck's node-oriented strategy separates steps into groups of Node or Workflow steps, and operates in chunks.  i.e. each Workflow step in the workflow is like a synch point, since it only happens once in the workflow.  Node steps can be dispatched separately to all the nodes, but Workflow steps cannot.

What you are seeing is that your first step is a Workflow job reference step, so it has to complete before the next Node step can proceed.  After all nodes complete the Node step (step 2), then it can proceed to the final step which is a workflow step.

**Comment by rophy** [comment]
Yes, it's working as you described, thanks a lot!

What has to be done:
1. Change Job Reference Step to run as "Node Step"
2. Set Node Filter to `${node.name}` so that it selects the same node as the triggering job
