### ISSUE TITLE
Can rundeck take place of crontab?

### ISSUE THREAD

**Issue by hustneverland** [rundeck/rundeck#1582]
hi all,i am new to rundeck.
i want to use rundeck to manage schedule jobs on other servers.

Now maybe i have two hundred lines on /etc/crontab likes \* \* \* \* \* /usr/local/bin/php root produceData.php >> /tmp/data.log

it will run every second.however if i set a scheduled job through rundeck installed on a machine called maser,the question is : 

everytime it runs /usr/local/bin/php root produceData.php >> /tmp/data.log ,need the master start firstly ssh to the target server?

if so, assume i have 200 php scripts need to run every second,the rundeck need ssh to the target server 200*60 times in a minites?

**Comment by biguphpc** [comment]
First I think questions like this are probably better posted on the mailing list instead on the issue tracker.
Short answer: Yes that would mean rundeck will ssh to 200 machines very minutes. It's doable, but what if one process takes longer than a minute to run ? what if there's a connection issue.

I think the problem here is how your scripts are designed. Right now, with cron if your process takes longer than a minute, multiple scripts will run in parallel and I'm not sure it's what you want. 

Rundeck is great to centralize scheduling and keeping logs but you should probably re-think this process before integrating it it in Rundeck. Maybe you can start it once every hour and it runs 60 times in a loop ? Can you make it run every hour instead of every minute? these are probable improvements you should think about.

**Comment by ahonor** [comment]
Please reopen if you still have this concern
