### ISSUE TITLE
SCM: GitExportPlugin - Could not serialize job: java.lang.IllegalArgumentException: Format not supported: yaml

### ISSUE THREAD

**Issue by schast** [rundeck/rundeck#1644]
I sometimes get an java.lang.IllegalArgumentException when commit a changed job. the changes are commited and pushed to the git repo without any error in the gui. the exception is only shown in the service.log

[2016-01-27 - Rundeck GitExportPlugin - Could not serialize job.txt](https://github.com/rundeck/rundeck/files/106722/2016-01-27.-.Rundeck.GitExportPlugin.-.Could.not.serialize.job.txt)

**Comment by gschueler** [comment]
was this using rundeck 2.6.2?

**Comment by schast** [comment]
yes

**Comment by gschueler** [comment]
fyi: i think this was caused by a race condition; after saving a job, an event is posted about it, and this triggers a call to scm plugins about the job change.  however, if it takes more than 5 seconds for hibernate session changes to flush (write to db), then the xml/yaml job serializer won't receive the updated data.  i was able to trigger this error after forcing a delay after the event is sent but before the changes flush.  

is it possible that saving a job takes longer than 5 seconds for your system?

working on a fix that doesn't trigger the event until after the changes are flushed
