### ISSUE TITLE
local-ssh-agent and local-ttl-ssh-agent only works on node configuration level

### ISSUE THREAD

**Issue by derorrim** [rundeck/rundeck#1723]
I set local-ttl-ssh-agent  on framework and project "level".
Neither of them worked, not even "ssh-agent" in debug job output.
When set at node level everything works as expected.

**Comment by linuxmail** [comment]
hi,

having the same problem: I configured on framework.properties and project settings the local-ssh-agent, but it seems to not working. The nodes list are coming from Ansible hosts, to I can't configure them directly.

**Comment by linuxmail** [comment]
hi,

because I have no idea from Java, I try to create a workaround and changing [this](https://github.com/rundeck/rundeck/blob/51e9e5f7d428f1a81688932e49a8a5d167f25f0f/core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/NodeSSHConnectionInfo.java#L307) line from false to true and build a new Debian package. I hope, that this issue can be fixed soon. May @ltamaster has an idea, what the root cause is :-)

**Comment by linuxmail** [comment]
Can closed, because this settings are only for the JSCH SSH.

**Comment by ltamaster** [comment]
I tested it and it is working as expected
