### ISSUE TITLE
Disable option substitution into scripts

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#1762]
It could be useful to be able to deactivate the feature to substitute option values into scripts with @option.foo@

This doesn't meet our security requirements, and we need to require the use of the RD_OPTION_\* environment variables instead.

**Comment by plambert** [comment]
+1 for this.

**Comment by solaryeti** [comment]
Based on the mention of security requirements, I assume this is referring to the ability to inject code via variables. As an example, given a job with an option called `foo` and a script step containing the following:
```bash   
#!/usr/bin/env bash
echo $RD_OPTION_FOO
echo @option.foo@
```

and passed "foo; ls -l /" to the `foo` option when running the job, you'd get the following output:
```
foo; ls -l /
foo
total 44
lrwxrwxrwx.   1 root    root       7 Mar 16  2016 bin -> usr/bin
dr-xr-xr-x.   4 root    root    4096 Oct  4 10:02 boot
drwxr-xr-x   19 root    root    3160 Nov  1 09:12 dev
drwxr-xr-x.  95 root    root    8192 Nov  1 09:12 etc
drwxr-xr-x.   4 root    root      33 Oct  3 09:40 home
[rest of output omitted
```
If so, I'd also like to either see an option to disable @option.*@ variables or to make them safe for use in scripts.

**Comment by ahonor** [comment]
This can be a global (e.g., framework) level configuration assuming it's undesired behavior for the whole app. Curious if anybody wants this configuration flag on a per project basis.

**Comment by danifr** [comment]
I do agree they can represent a security issue however it can be easily fixed if you just don't use them in your code.

Am I missing something?

**Comment by solaryeti** [comment]
@ahonor I'm happy for it to be global.
@danifr Unfortunately it isn't as simple as that once you have a larger or extended group of people editing or creating jobs. As an example, I went through all our jobs a couple of weeks ago and replaced all the \@option.foo\@ variables for $RD_OPTION_FOO. Earlier this week I discovered someone had created a new job with \@option.foo\@. That's why it would be nice to either have that be shell safe in scripts or be able to disable it completely so that I don't have to be constantly watching if someone has introduced it somewhere.
