### ISSUE TITLE
Rundeck service starts and goe to dead automatically. cannot login 

### ISSUE THREAD

**Issue by saiteja313** [rundeck/rundeck#1800]
[root@ rundeck]#service rundeckd start
Starting rundeckd:                                        [  OK  ]

[root@ rundeck]# service rundeckd status
rundeckd dead but pid file exists

**Comment by ilovemysillybanana** [comment]
Did you install this via a cookbook? I had a similar issue but I found a work around.

**Comment by alwinmark** [comment]
@ilovemysillybanana  what was the work around? Ive the same problem right now with puppet

**Comment by ahonor** [comment]
Please reopen if this remains a concern

**Comment by ilovemysillybanana** [comment]
@Hima-kiran Are you able to post code? It's been a couple years but I'd be willing to look through it if you post what you're doing.

**Comment by Prempatrick** [comment]
Can you please reopen this?

**Comment by kalaivairamuthu** [comment]
0

I have faced the same problem and i resolved it by changing ownership to the rundeck related folders.

1)    Remove the /var/run/rundeck.pid file in order to delete the zombie process.
2)   Check for any other zombie process using lsof commmand.
3)    Reownership the rundeck related folders (Owner should be rundeck)
4)    Restart the rundeckd service.
5)    Hurray!!! its running inside the container well.
