### ISSUE TITLE
Questions regarding building source

### ISSUE THREAD

**Issue by johnpaularthur** [rundeck/rundeck#1810]
I'm on a Mac and followed the wiki instructions for build environment, but rundeck still won't build (fails on unit tests).  I did get it to build on a docker (centos).  Has anyone successfully built this on a Mac?

Also, I'm looking to customize the UI, but even with a successful build on the docker image, my changes won't take.   I'm not familiar at all with grails, so this is new for me.  I thought I should be able to edit the gsp files under rundeckapp/grails-app/views, then clean/build.  But still nothing changes in the rundeck-launcher jar.   What am I doing wrong?

**Comment by fdevans** [comment]
We apologize if this issue was missed.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
