### ISSUE TITLE
2.6.8 on windows fails on pluginJars dirs

### ISSUE THREAD

**Issue by niphlod** [rundeck/rundeck#1898]
Updated from 2.6.7 to 2.6.8, 2.6.8 launched on Windows fails with multiple repetitions of this error

 java.nio.file.FileSystemException: C:\RUNDECK\var\tmp\pluginJars\20160615155414974-rundeck-stub-plugin-2.6.8.jar

launching 2.6.7 works perfectly

**Comment by niphlod** [comment]
this is probably the commit to blame 2dd38d6fa2894709832e8eec9ac9faba6ffa406d

**Comment by gschueler** [comment]
hi, do you have a stacktrace for the error?

**Comment by niphlod** [comment]
yep. this is for a single .jar but basically for every plugin there's a similar stacktrace
[issues_1898.txt](https://github.com/rundeck/rundeck/files/316581/issues_1898.txt)

**Comment by gschueler** [comment]
our jar plugin code seems to copy the source plugin to a "cache" file using timestamp.  I think we need to fix that, either to use AtomicLong counter instead of timestamp, or remove/improve the caching code.

It seems like two threads are writing to the same cache file. On unix, the destination file seems to get overwritten without error (although there are some other possibly related issues **), but on Windows this causes an error
