### ISSUE TITLE
[Options Providers] 2.6.9 - display of sorted options does not respect "preserveOrder" or definition settings

### ISSUE THREAD

**Issue by katanafleet** [rundeck/rundeck#1998]
We were waiting for 2.6.9 options provider improvements thanks a lot.
Unfortunately, it seems that options are not always sorted in defined order that has been set in GUI or XML "preserveOrder" tag ?  

We have the issue when there's dependencies between option A => B so B is displayed before A even if we set A before B in the GUI.

Simple options can also be mixed between definition and display ...

cf. job sample zip and attached and screenshots associated.

![2016-08-10 14_56_18-rundeck - edit job](https://cloud.githubusercontent.com/assets/6132120/17554750/b6bc1240-5f0c-11e6-9672-d849830e9139.png)
![2016-08-10 14_53_10-rundeck - prepare](https://cloud.githubusercontent.com/assets/6132120/17554757/ba67ad50-5f0c-11e6-818f-4e735e7a1e74.png)
[Prepare.zip](https://github.com/rundeck/rundeck/files/411106/Prepare.zip)

**Comment by gschueler** [comment]
Since the GUI manual ordering is now available, I'm going to change the behavior to this:

* always show options in the order defined

The sorting was intended to automatically put the options in the natural order based on the cascading order, however that was when there was no way to manually order them in the GUI.  Now that you can do that it makes more sense to just use that ordering always.
