### ISSUE TITLE
Feature request: EC2 Run Command node executor

### ISSUE THREAD

**Issue by jhmartin** [rundeck/rundeck#2006]
Rather than rely on SSH connectivity, allow the use of the EC2 Run Command / 'Simple Systems Management Service' (SSM) agent to pass commands to nodes. This allows rundeck to execute commands on EC2 nodes where it does not have direct connectivity. It also avoids the need to give Rundeck SSH shell privileges to nodes.

http://docs.aws.amazon.com/ssm/latest/APIReference/Welcome.html

**Comment by gschueler** [comment]
this could be part of the ec2-nodes plugin, i.e. could bundle them together and optionally enable it for any ec2 nodes

**Comment by mattmauriello** [comment]
So, this is something I've been thinking of tackling for some time, and i dont think it would be too difficult to do as a plugin. based on my understanding, it we'd have to handle 2 things: the file copier, and the node executor.

As I understand, for rundeck to run a script on a node, it needs to first copy the script to the target node, then, using the executor, it runs the script that was staged. in an AWS world, I imagine i would want to handle it as such:
file copier:
since the script could be arbitrarily large, I don tthink it would be wise to try to pass it directly to the 'runShellScript' document. instead, take the generated script output and stage it directly to S3, at a location any instance would have access to read.
node executor:
i would create an SSM document that takes in the s3 location of the script, desired log location in S3, and the user to run as, and the document would simply downloaded form s3 and run it as the user specified (since the SSM agent runs as root and we may want to respect the "user" field from the nodes). once execution is complete, get the log from S3 and return it to rundeck.

Hoping someone with more intimate knowledge of the process can set me straight if my understanding is off.

**Comment by mattmauriello** [comment]
@gschueler,
As im sure you know, when using Ssm for running commands, they're returned as a single result set, not streaming. Does the node executor script plugin engine allow for any log formatting so that I can override the time stamps in the lines? If so, that would be a clean way to get the whole output dumped back to rundeck but still have useful time stamps show in the console, as opposed to all showing the time when the job finished and logs were retrieved from ssm.

**Comment by jordo1138** [comment]
any movement on this?

**Comment by abeluck** [comment]
Our organization has mostly completed the transition from SSH+bastion access to only accessing EC2 nodes with the AWS SSM Run Command feature  (and session manager for remote shells).

I was evaluating Rundeck for our ops usage, but without this feature we can't access most of our nodes.

**Comment by jsboak** [comment]
This has now been addressed in our 4.0 Release [(release notes)](https://docs.rundeck.com/docs/history/4_x/version-4.0.0.html#plugin-enhancements) with the new Systems Manager Node Executor and File Copier plugins [(docs here)](https://docs.rundeck.com/docs/manual/projects/node-execution/aws-ssm.html).
