### ISSUE TITLE
Setting content-type on GET requests generates exception

### ISSUE THREAD

**Issue by lusis** [rundeck/rundeck#2009]
During a rewrite of my golang library to rundeck, I added support for optional content types (required for downloading stuff from the storage endpoints.

During testing I discovered that blindly setting the content-type on GET requests returns and exception:

```
<result error="true" apiversion="17">
<error code="api.error.parameter.error">
<message>Some parameters were invalid: Error occurred initializing command object [query]. org.xml.sax.SAXParseException; Premature end of file.</message>
</error>
</result>
```

If I remove the `content-type` header, the call works:

```
<jobs count="2">
<job id="f6c26444-59e6-4eec-878a-7c6986910dcf" href="http://localhost:4440/api/17/job/f6c26444-59e6-4eec-878a-7c6986910dcf" permalink="http://localhost:4440/project/jv_test_project/job/show/f6c26444-59e6-4eec-878a-7c6986910dcf" scheduled="false" scheduleEnabled="true" enabled="true">
<name>test</name>
<group>test_jobs</group>
<project>jv_test_project</project>
<description>This is a test job</description>
 </job>
<job id="153a5d54-efdc-45f0-91e7-6b24322ac9ac" href="http://localhost:4440/api/17/job/153a5d54-efdc-45f0-91e7-6b24322ac9ac" permalink="http://localhost:4440/project/jv_test_project/job/show/153a5d54-efdc-45f0-91e7-6b24322ac9ac" scheduled="false" scheduleEnabled="true" enabled="true">
<name>test1</name>
<group />
<project>jv_test_project</project>
<description>This is a test job</description>
 </job>
 </jobs>
```

I haven't reviewed the HTTP spec on this but I've never seen this in the past where a content-type header causes problems on get. I also haven't dug into the code yet to find WHERE this happens. 

Regardless my understanding thus far is that headers not used for a specific request shouldn't be used?

**Comment by gschueler** [comment]
I believe `content-type` is not supposed to be used for GET requests (which have no body), but, also haven't looked at the spec.

I'm guessing the problem is a Grails thing.. the specific endpoint you were trying is defined with a "Command object" (java object) which Grails attempts to fill in via request parameters.  Specifying a content-type may be triggering it to try parsing the body for the values to fill into the object.  Seems very weird it would do that for a GET request tho.

Was it `application/xml` content-type specifically?

... Ok looks like this is definitely a grails bug: https://github.com/grails/grails-core/issues/10095

**Comment by lusis** [comment]
Awesome thanks!

I've worked around it for now and it's not a huge blocker. Just took me forever to track down.
