### ISSUE TITLE
error deleting jobs after adding via api

### ISSUE THREAD

**Issue by johnpaularthur** [rundeck/rundeck#2063]
using 2.6.9-1.GA (centos)

I am testing out the utilization of the api to upload thousands of jobs created in yaml format.  This worked fairly well, but once I try to delete them all thru the GUI, i get this error on some of them but not all (the context of the error changes depending on the job it is trying to delete):

`ERROR: update or delete on table "scheduled_execution" violates foreign key constraint "fk_jraxrdpul0ne9eediy1xjlsfv" on table "rdoption" Detail: Key (id)=(22916) is still referenced from table "rdoption".`

Any reason why this would occur?  Should this be a cascade delete?

**Comment by gschueler** [comment]
yes, the rdoption values should be deleted when the job is deleted.  was this using the Bulk delete GUI action?

**Comment by ahonor** [comment]
Please reopen if this remains a concern

**Comment by aaaronic** [comment]
I am also seeing this issue. Deletes via API and the GUI both have the same issue. Any clue how to help aside from manually deleting from the database?

**Comment by aaaronic** [comment]
So I'll provide a possible solution that worked for me:

Somehow, we had duplicated options on the job (the job is modified by Terraform often) when I looked in the database. I manually deleted the visible options on the job in the "Edit job" UI. After I did that, the duplicated options showed up in the UI (they had been invisible in the database before -- no clue why/how). Then I was able to delete the job just fine through the UI.

To be clear, I noticed the additional, hidden options in the the database but was ultimately able to fix everything through the UI instead of having to manually edit the db.
