### ISSUE TITLE
2.6.10: Inline script token expansion breaking perl

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#2185]
# Bug report

via https://github.com/rundeck/rundeck/issues/2021#issuecomment-261463049

~~~{.perl}
sub perlFunction {
    ...
    return \@files;
}
~~~

the script would now be generated without the backslash:

~~~{.perl}
sub perlFunction {
    ...
    return @files;
}
~~~

**Comment by schast** [comment]
> @gschueler would you prefer a way to disable it completely?

no, i need to replace the @ tokens in inline scripts.

i think the problem was generated with the fix in #1823.
before the fix in #1823 allowed characters was **alphanumeric** and **`.+-_:`**
now all characters are allowed which are no whitespace, right?
what characters are allowed for the `${ctx.name}` syntax?

in my case their is only one @ in the line:
```
sub perlFunction {
    ...
    return \@files;
}
```
why this is affected?


possible solution:
- `\@` should escape the @ token expansion.
- define allowed characters for the @ tokens like this: **alphanumeric** and **`.+-_:/`**

**Comment by gschueler** [comment]
there is a bug affecting `\@`. But, the fix is that we have to have a global escape character, so `\` followed by any char will always output the second char., so your example would require `return \\@files;`, and any `\` in your code would also have to be escaped as a double backslash.

**Comment by gschueler** [comment]
other solution: require double `@` to be expanded as literal `@`
