### ISSUE TITLE
API filtering not working for /api/17/project/[PROJECT]/jobs

### ISSUE THREAD

**Issue by niphlod** [rundeck/rundeck#2322]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.7.1
* install type: launcher
* OS Name/version: WS2012R2

**Expected Behavior**

using ?scheduledFilter=true to be returned only jobs with scheduled executions

**Actual Behavior**

the full list of jobs to be returned

**How to reproduce Behavior**

call /api/17/project/[PROJECT]/jobs?scheduledFilter=true

**Comment by gschueler** [comment]
i'm not able to reproduce that issue, i see the correctly filtered list.

using curl:

    curl -H x-rundeck-auth-token:$RD_TOKEN http://ecto1.local:4440/api/17/project/ctest/jobs?scheduledFilter=true

I get 2 results.  without the `scheduledFilter=true` I see all jobs in the project.

How are you making the query?

**Comment by niphlod** [comment]
huh. thanks for the pointer....with that notation I only get the correct result, too. 

I was passing by default a "Content-Type" header set to application/json (a leftover from other methods that POST parameters in json).

The thing is 

    curl -H "Accept: application/json" -H "Content-Type: application/json"  /api/17/project/[PROJECT]/jobs?scheduledFilter=true 

returns unfiltered jobs, while 

    curl -H "Accept: application/json" -H "Content-Type: application/json"  /api/17/project/[PROJECT]/jobs?scheduledFilter=true 


works as documented

dunno if it's expected.

**Comment by gschueler** [comment]
@niphlod ah, I think the `Content-Type` might be the problem.  `GET` requests have no body, so they should have no Content-Type.  However there is a bug in grails (see https://github.com/rundeck/rundeck/issues/2009) which still takes it into account, so it is probably interfering with the URL parameters, because it thinks there is a json body to use for the input data.  For now it is best to not use a `Content-Type` header when doing a `GET` request.

**Comment by niphlod** [comment]
perfect. sorry for the wrong report. The fact that it replied correctly (just without filtering) made me think there were no issues in the call itself
