### ISSUE TITLE
Rundeck encloses single quotation to string with Variable and Special Character

### ISSUE THREAD

**Issue by jaymence** [rundeck/rundeck#2520]
I'm running Rundeck2.8.2 on Windows2008. Im trying to execute a command:
![image](https://cloud.githubusercontent.com/assets/28796597/26229974/1edc9fcc-3c78-11e7-940e-8c806a896454.png)

When I run the job using STUB setting, Rundeck already appends the single quoation in the string:
![image](https://cloud.githubusercontent.com/assets/28796597/26230010/59c0a89a-3c78-11e7-89a4-ae4d4274a253.png)

Running the command in the the linux node, makes it already invalid:
![image](https://cloud.githubusercontent.com/assets/28796597/26230052/ad07cf60-3c78-11e7-919b-3fb5ec4cfbfa.png)

Executing the command manually in the target server has the same result:
![image](https://cloud.githubusercontent.com/assets/28796597/26230091/f714059c-3c78-11e7-9039-679b0c07dcee.png)

I think this only happens when a string has an ${option.VAR}. Putting a special character will enclose the string with single quotation. is there a way to prevent this?

**Comment by gschueler** [comment]
rundeck will automatically quote argument values when expanding argument variables if they expanded value contains any unix special chars (`"';{}()&$\|*?><`) so since you have a `*` it will quote it.

If you use an inline script you can construct the command in a different way to use the variables that are available

~~~ {.bash}
#!/bin/bash
DIR=$1
NAME=$2
DT=$3
PATH=${DIR}${NAME}_exp_${DT}*
ls -lh $PATH

~~~

arguments: `${option.SBLDBBKPDIR} ${option.SBLDBNAME} ${option.DT}`
