### ISSUE TITLE
Job delete/rename: should check whether any job references would break

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#257]
Job references might break if you delete/rename/move a job, so when doing that it should check to see if there are any references that might break and warn you.

**Comment by biguphpc** [comment]
Maybe rundeck could use the UUID of the job instead of the name when referencing the job ? This way renaming the referenced job would not break the workflow anymore. 

best part is that exporting/importing jobs could be backwards compatible since jobs could be referenced by name like before 

```xml
<jobref name="nextjob" group="some/group"/>
```

or by UUID

```xml
<jobref uuid="fd9c1d70-a494-4a32-a36f-860caf512eac">
```

**Comment by ahonor** [comment]
+1

**Comment by mumblez** [comment]
+1

**Comment by mathieuchateau** [comment]
+1

**Comment by awainer** [comment]
+1

**Comment by danifr** [comment]
+1

**Comment by methom90wh** [comment]
+1
