### ISSUE TITLE
I cannot use the node.name variable in a job reference

### ISSUE THREAD

**Issue by ext94053** [rundeck/rundeck#2591]
Issue type: Bug report/Enhancement Request

My Rundeck detail

* Rundeck version: 2.7.3.1
* install type: (rpm,deb,war,launcher?) launcher
* OS Name/version: 2.6.18-371.1.2.el5 Red Hat
* DB Type/version: mysql? postgres? h2?..

**Expected Behavior**

I cannot use the node.name variable in a job reference

**Actual Behavior**

The variable node.name does not change

**How to reproduce Behavior**

Job A: I try modify the node.name depending the options:

if [ ""@option.Opcion@"" = "Opcion1" ]; then
    RD_NODE_NAME=MOL18P13
elif [ ""@option.Opcion@"" = "Opcion2" ]; then
    RD_NODE_NAME=MOL18P44

Then, I pass the variable in arguments

Job B (job reference): I execute the job with the node filter: ${node.name} but node.name does not have the desired value.

**Comment by dpomnean** [comment]
I've had this same issue before, try using ${node.fqdn} instead

**Comment by gschueler** [comment]
you can't change the node name of the currently executing node.  Changing a bash environment variable will have no effect outside of the script execution within that step.

If you want to pass a data value to another step in a workflow, rundeck 2.9.0 will have that feature.

**Comment by ext94053** [comment]
Hi

I have the Rundeck 2.11.5-1 version but, i don`t know how to use this functionality, can you help me?

Thanks a lot

**Comment by ecarrascos** [comment]
@ext94053 if you refer to the "Data Passing" functionality, that allows you to pass data to another step, you can check these links:
[2.9.0 feature introduction](https://github.com/rundeck/rundeck/issues/2577)
[Data Passing preview Video](https://www.rundeck.com/blog/output-processing-data-passing-preview)
[Uplift variable to Global](https://github.com/rundeck/rundeck/pull/2952)

And [this StackOverflow question](https://stackoverflow.com/questions/49916670/json-as-key-value-and-pass-between-steps-in-rundeck) could be helpful as well.
For new questions, I recommend you to check [this link](http://rundeck.org/help.html), as this issue was closed almost a year.
Hope it helps!
