### ISSUE TITLE
Global filter : Render formatted data

### ISSUE THREAD

**Issue by niphlod** [rundeck/rundeck#2690]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.9.2
* install type: launcher
* OS Name/version: WS2012R2
* DB Type/version: MSSQL

**Expected Behavior**
Markdown tables are supported

**Actual Behavior**
Markdown tables are not supported

**How to reproduce Behavior**
echo in a step 
```
| col1 | col2 | col3 | col4  | col5  |
|---|---|---|---|---|
| value1 | value2 | value3 | value4  | value5  |
```
it doesn't render as a table (e.g. in GFM)

| col1 | col2 | col3 | col4  | col5  |
|---|---|---|---|---|
| value1 | value2 | value3 | value4  | value5  |

This could a nice table output with hyperlinks to e.g. other rundeck jobs.

**Comment by gschueler** [comment]
the builtin markdown renderer uses markdownj library, another plugin could be created that supports GFM via another lib

**Comment by niphlod** [comment]
whoops sorry, I thought it was "easy" to include the same library that renders the job description, since it works perfectly fine there

**Comment by gschueler** [comment]
I know it is not the same, but as a workaround you could emit CSV data tagged as such and Rundeck would render that as a table for you.

**Comment by niphlod** [comment]
json works too, but it can't "prepare" clickable links. The only way to go there currently is rendering a full fledged HTML table, which can be cumbersome to create and display correctly within the HTML coming from rundeck itself.

**Comment by gschueler** [comment]
Yes, I see how it would be more convenient to use markdown.  The Job "runbook" sections are rendered using Markdeep (a javascript in-page renderer) So perhaps it would be simple to enable that for the log output as well

**Comment by damageboy** [comment]
I would actually vote for using a proper server-side rendering of markdown that Sucks Less© for the single purpose of being able to send the rendered HTML as e-mails when something fails...

**Comment by gschueler** [comment]
@damageboy yes, a good consideration

**Comment by damageboy** [comment]
Is there a reason not to switch the default markdown renderer from markdownj to something else like
[commonmark-java](https://github.com/atlassian/commonmark-java)?

It seems to support just about anything imaginable in markdown and being actively developed...

Any thoughts?

**Comment by gschueler** [comment]
@damageboy no reason, if that is better perhaps submit a PR.

**Comment by damageboy** [comment]
@gschueler I'll give it a go...

**Comment by damageboy** [comment]
@gschueler do you know if the [IDEA/IDE instructions](https://github.com/rundeck/rundeck/wiki/IDE-Development-Environment) are up to date?

I'm not sure they are matching up with my experience with IDEA as I'm following it along..

**Comment by gschueler** [comment]
@damageboy what problem are you having?  I revised that doc to specify grails version 2.5.6, but otherwise it looks ok to me

**Comment by damageboy** [comment]
The problems I'm experiencing may be related to Windows...

When I run from the command prompt:
```
gradlew build -x test
```
everything build to completeness (Many unit tests fail on Windows, but that's unrelated for now)

When I try building with IDEA 2017.2, after importing the gradle build into IDEA I get lots of unresolved symbols, for example in ContextView.java:

![image](https://user-images.githubusercontent.com/125730/30519552-048ed0b6-9ba2-11e7-9ccc-47d398d17175.png)




 but when I try building the project in IDEA I get the same (lots of) the same type of error:
![image](https://user-images.githubusercontent.com/125730/30519556-221e35ae-9ba2-11e7-8ba4-da94ad5b6561.png)


I'm sure there's some step I'm missing from the [IDE Setup](https://github.com/rundeck/rundeck/wiki/IDE-Development-Environment) page, mostly because it seems to be outdated w.r.t to my IDEA version...

**Comment by damageboy** [comment]
Hi all, I've kind of managed to get this done...

The only issue, as far as I'm concerned is that the rendered markdown looks kind of ugly...:
![image](https://user-images.githubusercontent.com/125730/30530725-e0b499cc-9c51-11e7-83c9-b6e0360dcf5d.png)

In case it's not clear, right there, in the center of the screenshot there's a table:

![image](https://user-images.githubusercontent.com/125730/30530748-07c473a2-9c52-11e7-96ac-32a463ff359b.png)

How should / can we improve the table rendering?
Is it OK to bundle a github like css for markdown tables in the code?

Would you like me to attempt limiting the css to the redered markdown only?
Any sort of input will help...

**Comment by damageboy** [comment]
I did a mockup, and it would appear that if I use https://github.com/sindresorhus/github-markdown-css and enclose the markdown in `<article>` + `</article>` tags, the rendered markdown looks much better (In my opinion):

![image](https://user-images.githubusercontent.com/125730/30530961-b6ecee58-9c53-11e7-82b0-65241b2ecc3e.png)

Is this something that rundeck devs are comfortable with me including in rundeck pages served for the purpose of nicer looking markdown?

**Comment by damageboy** [comment]
OK, I just submitted #2768

Feel free to close this issue (I think) if you are fine with the PR.

**Comment by gschueler** [comment]
@damageboy re: IDE setup, for the core library and Grails, you may have to do this: Open the Project Structure view, select the "rundeckapp" module, and in the Dependencies tab, do "Add Module Dependency"  Select the "core_main" module, and add it as a dependency.  (Also for "rundeck-storage-filesys_main" if you have issues with the rundeck.storage.* classes).  Then move it in the dependency list to the top above the "Grails User Library".  This is a chicken/egg situation I think where the grails app depends on the core (and storage-*) jars version x.y.z-SNAPSHOT, but they are not available via Maven repo, so it cannot resolve them.  If you add as a dependency the IDE will resolve the missing classes.   When you want to run the app via the IDE, you will have to do `./gradlew -p core install` and the same for rundeck-storage subdir, so that the x.y.z-SNAPSHOT jars are at least available in local m2 repo.

**Comment by gschueler** [comment]
For HTML table rendered in markdown, the rundeck CSS (based on Bootstrap) doesn't have a style for unclassified Table tag.  If you could add a `class="table"` it would probably appear nicer.  For the "formatted data" converter plugins, like CSV, I use these classes: `table table-condensed table-bordered table-embed table-data-embed`.  Not sure if the GFM plugin lets you declare some default css classes to use?
