### ISSUE TITLE
Jobs Error (Error applying layout : base)

### ISSUE THREAD

**Issue by stoddartjamie** [rundeck/rundeck#2812]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.9.3-1
* install type: rpm
* OS Name/version: CentOs 6
* DB Type/version: postgres.

**Expected Behavior**

We use Chef to install Rundeck and are trying to upgrade to 2.9.3, however we are unable to get to the jobs pages, getting error above.

**Actual Behavior**

![image](https://user-images.githubusercontent.com/32703325/31437391-0557dd74-ae7d-11e7-8ed1-1b544f4cd9c8.png)
[service.log](https://github.com/rundeck/rundeck/files/1375372/service.log)

**How to reproduce Behavior**

**Comment by stoddartjamie** [comment]
As an addition it seems the projects created by Chef via the rd tool (fine in older version of Rundeck) are the ones failing.

If we manually create a new project there is no issue, I will further investigate any differences.

**Comment by gschueler** [comment]
The log indicates it is having a problem loading the encrypted project config data from the database.  The decryption fails which could be due to a number of causes, unfortunately there is no  indication of what that cause is.

possibly: the decryption password is wrong, or the specific algorithm used for decryption is not available.

**Comment by stoddartjamie** [comment]
Hi,

I passed on your comments to the team running the build and they had set encryption which caused anything we imported to fail, this has been removed and now all is good.

Thanks

Jamie
