### ISSUE TITLE
Resolve vars in secure storage path

### ISSUE THREAD

**Issue by ssegovia** [rundeck/rundeck#2878]
Issue type: Bug report/Enhancement Request

Hi, I am trying to pass credentials to a script

Using a Option with input type Private I try to get the password but I'm not able to get this credentials if I pass a var in the path of key storage.

This not work:
![image](https://user-images.githubusercontent.com/25898060/31894608-3cc2505a-b80f-11e7-8a74-5901646745bd.png)

![image](https://user-images.githubusercontent.com/25898060/31894645-524c3904-b80f-11e7-81c9-f97a3bf2c420.png)

This is the var in exec environment and the current keystorage 

![image](https://user-images.githubusercontent.com/25898060/31895040-71a8366c-b810-11e7-816c-95b260b8e101.png)

![image](https://user-images.githubusercontent.com/25898060/31895103-9502a1ba-b810-11e7-8f99-812972e02da8.png)

If I select the individual key in the storage this works, so I can't automatize the script :/

**My Rundeck detail**

* Rundeck version: 2.9.4-1
* install type: rpm
* OS Name/version: Centos 7 
* DB Type/version: Mysql

**Expected Behavior**

Rundeck must resolve the var and get the correct password

**Actual Behavior**

Rundeck not get the key

**How to reproduce Behavior**

**Comment by puremourning** [comment]
Is your step a `nodeStep` (i.e. set to "dispatch to nodes" ) ? IIRC you can only use `node` context vars in `nodeSteps`

**Comment by robgott** [comment]
I think this issue is just regarding generally using vars in the default key path for a secure option, it would be great for example to use `keys/users/${job.user.name}`
for example in our use case we want users to be able to upload their public key to key storage and then one of the steps in the job is a script adding that key to ssh auth keys on a dynamically provisioned host.
