### ISSUE TITLE
Log filter key-value data passing can't be used as arguments to Workflow Step Job Reference

### ISSUE THREAD

**Issue by snifbr** [rundeck/rundeck#2968]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.1-1
* install type: rpm
* OS Name/version: CentOS 7.4.1708
* DB Type/version: mysql

**Expected Behavior**

- When I pass key-value variable to **Workflow Step Job Reference** via argument - the value should be replaced by captured key-value data.
example argument in job reference: `-LoginPass ${data.LoginPass}`

**How to Reproduce**

- Problem: When I am passing key-value variable to **Workflow Step Job Reference** via argument - the value isn't being replaced by captured key-value data, only when I using **Node Step Job Reference** the value is being replaced.

**Comment by ahonor** [comment]
@snifbr can you provide your job definition

**Comment by snifbr** [comment]
Sure @ahonor.

JobDefinition.yaml: https://gist.github.com/snifbr/69965ba6f7e57dc1e396829b826b2344

**Comment by gschueler** [comment]
since the first step is a script executing on a Node, the value is captured in the node's context.

you can either use the node name `${data.LoginPass@mynode}` or since you are not dispatching the job and it would only execute on one node, you can use the `*` expansion to collect all node values (in this case only one): `${data.LoginPass*}`

does that work for you?

**Comment by snifbr** [comment]
Thanks @gschueler, now this work perfectly!

Then sorry, is only my fault, not a bug.

If someone can asnwer, just more one question ->
* Is there a better documentation about data passing than this "https://github.com/rundeck/rundeck/issues/2577"?

**Comment by gschueler** [comment]
@snifbr i will add an issue to improve documentation
