### ISSUE TITLE
SSHProtocolFailure: channel is not opened

### ISSUE THREAD

**Issue by rajaluo** [rundeck/rundeck#3067]
Issue type: Bug report

**My Rundeck detail**
channel is not opened.
Failed: SSHProtocolFailure: channel is not opened.
Execution failed: 3047505 in project qukan: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [q-3:SSHProtocolFailure: channel is not opened.]}, Node failures: {q-3=[SSHProtocolFailure: channel is not opened.]}, status: failed]
--

* Rundeck version: 
2.8.2
* install type: (rpm,deb,war,launcher?)
Yum RPM Install
* OS Name/version: 
centos7
* DB Type/version: mysql? postgres? h2?..
mysql

**Expected Behavior**

**How to Reproduce**
random occur

**Comment by sedmaster** [comment]
I can confirm this.

Saw this error message on 2.6.6.1 and is currently also occuring randomly in 2.10.6-1. The problem started to emerge just a few weeks ago (around 8th of Feburary). 2.6.6 did't make any problem till this date. So I suspect it could be a bug triggered in Rundeck (maybe jsch library?) due to an external software change.

Job connects server and serivice running
* Red Hat Enterprise Linux Server release 6.9 (Santiago)
* OpenSSH_5.3p1, OpenSSL 1.0.1e-fips 11 Feb 2013

**Comment by pshlykov** [comment]
Same here. The issue pops up occasionally, maybe once a week, certainly not daily.

* Rundeck version: Rundeck 2.10.7-1
* Install type: Yum RPM Install
* OS: Oracle Linux Server 7.3
* OpenSSH_6.6.1p1, OpenSSL 1.0.1e-fips 11 Feb 2013
* DB Type/version: EDB Postgres AS 9.6

Thanks!

**Comment by sedmaster** [comment]
This had most probably nothing to do with Rundeck. The client had issues with its Cisco switches. After patching them we haven't seen this failure again. Thanks.

**Comment by hostadmin** [comment]
@sedmaster, could you post link to Cisco switches issues. We got same problem and we like to patch our switches as well, but I didn't find something about that

**Comment by sedmaster** [comment]
@hostadmin, since this is the clients' network, there was no precise maintenance note. It just stated "software upgrade to Nexus 5000 Switches" around Feb, 28th.
