### ISSUE TITLE
Rundeck Job timed out with java.lang.interuptedException***

### ISSUE THREAD

**Issue by rajivjackz17** [rundeck/rundeck#3085]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version:  2.6.3
* install type: (rpm,deb,war,launcher?) launcher
* OS Name/version: Linux
* DB Type/version: Oracle 

**Expected Behavior**
Job should run successfully in rundeck without timed out.

Actual Behavior **
[lxpcbwtpd09: Unknown: java.lang.InterruptedException]}, Node failures: {sxpcbwtpd09=[Unknown: java.lang.InterruptedException]}, status: failed]
14:16:15 [ABC][ERROR] Execution failed: 656445: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes:
[sxpcbwtpd09: Unknown: java.lang.InterruptedException]}, Node failures: {sxpcbwtpd09=[Unknown: java.lang.InterruptedException]}, status: failed]

**How to Reproduce**
not sure.

 Please anyone could share for resolution asap.

**Comment by doniz** [comment]
I have similar issue. My stack is under Docker container and the versions are:

```
APIVERSION : 48
BASE : /home/rundeck
BUILD : 5.4.0-20240618
BUILDGIT : v5.4.0-0-gb356f0f
VERSION : 5.4.0-20240618
ARCH : amd64
NAME : Linux
VERSION : 6.5.0-1024-gcp
IMPLEMENTATIONVERSION : 11.0.23+9-post-Ubuntu-1ubuntu122.04.1
NAME : OpenJDK 64-Bit Server VM
VENDOR : Ubuntu
VERSION : 11.0.23
```

The job in average runs about 35-40min, but sometimes if there are a peaks, it can last about 1,5h. So the timeout is set for 2h. My SSH setting: `framework.ssh.timeout` is 0. It fails the same way as described in the original issue, however it depends by the timeout. Setting timeout 2h with earlier completion, it hangs for 2h and then throw that error. 

I found the issue #3049 were @benishak has mentioned to disable either orchestration or parallel execution, in our case we indeed uses orchestration to randomly choose a single VM instance in the GCP to execute the job, because for some machines we have distribution and backgrounds tasks replicates between several machines. By disabling orchestration the task has succeeded. So it's indeed the bug in Rundeck where it can't listen the job signals with orchestration enabled.

Worth to mention for a reproducibility we in our company migrating Rundeck version from `3.3.3`  to `5.4.0`, and on the new version issue has started. On old Rundeck version this issue is not experiencing even tho orchestration is enabled for us. 

I can provide configuration if necessary, just let me know.
