### ISSUE TITLE
Email for onfailure sent when execution was successful

### ISSUE THREAD

**Issue by danielmroberts** [rundeck/rundeck#3105]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: Rundeck 2.10.0-1 
* install type: deb
* OS Name/version: Ubuntu 16.04.3 LTS
* DB Type/version: mysql (local)

**Expected Behavior**
We have each job setup to send an email notification on failure. The expectation would be that we only receive a notification when a failure occurs.

**Actual Result**
Just about every day, out of thousands of executions, we get a few notifications from the failure alerting. However when we open the email it actually says the job succeeded. I have updated the onfailure subject lines across all jobs to include ${execution.status} instead of having "Failure" static so we know it is a false alarm just from the subject (edit: I assume the subject will be sent with same status as in body of message but can't confirm yet as have not received email since the recent update).

**How to Reproduce**
Unknown, However it usually occurs at times where multiple jobs would be triggered. For example it is nearly always the case that if we have a job1 hit every 5 minutes and two jobs that hit every hour on the hour, then if job1 triggers an incorrect onfailure email it will occur on the hour.

**Comment by danielmroberts** [comment]
For onfailure notification emails sent when they shouldn't be, the subject line ends up having "scheduled" as the output for ${execution.status}.

**Comment by adam-nielsen** [comment]
I've just noticed this issue as well.  All the successful jobs that sent error e-mails have an execution time of zero seconds, while the ones that succeeded and did not send any error e-mails have execution times ranging between 0s and 15s.

Could it possibly be that the job completes so quickly that a later check thinks the job has failed and the next one is now scheduled?

**Comment by adam-nielsen** [comment]
Just confirming this indeed is the issue.  A workaround is to add `sleep 2` as an extra local command in the job so that it takes at least one second to run.  This completely stopped the error e-mails arriving for successful jobs for me.

As a side note, many of the e-mails said the job took -1 seconds to run, however I don't think this is the actual problem as some of the incorrect e-mails still said run time was 0 seconds.  Either way it looks like some sort of race condition where the job finishes before Rundeck checks its status.  Note that Rundeck still reports the job as having completed successfully through the web interface, it's just the error e-mail gets sent when it shouldn't.  Everything else seems to work as expected.

I guess the instructions to reproduce this problem would be to create a job that runs a single command like `echo` or `true`, and have it send an e-mail on error.

**Comment by josephtaylor-mn** [comment]
I am having this issue on Rundeck 3.1.0-20190731 installed on Debian. Getting slack error messages on successful executions.

**Comment by carlosrfranco** [comment]
@danielmroberts  I couldn't reproduce this on last version. Are you still having this issue?
Thanks

**Comment by danielmroberts** [comment]
We are a number of versions back so I'm not able to confirm.

**Comment by carlosrfranco** [comment]
Ok. So I recommend trying the latest version if possible, and let us know if you still find this issue, please.

**Comment by cs-rb** [comment]
We were having this issue with Rundeck 3.1.3-20191204 I added a sleep(1) to the code and that seems to have fixed it. When I have time I'll update rundeck and report back if it fixed the issue.
