### ISSUE TITLE
SCM git-import plugin limits jobs per YAML file

### ISSUE THREAD

**Issue by GroovyCarrot** [rundeck/rundeck#3139]
Issue type: Bug report
* Rundeck version: 2.10.6-1
* install type: deb
* OS Name/version: Linux 4.4.0-112-generic
* DB Type/version: local + LDAP

The YAML job specification states you can have multiple jobs per file:
http://rundeck.org/docs/man5/job-yaml.html#structure

However due to these lines, it seems that you explicitly can't:
https://github.com/rundeck/rundeck/blob/3673ca9a6cd6e52a4129b460f89735b5fb00f07a/rundeckapp/grails-app/services/rundeck/services/scm/ScmJobImporter.groovy#L62-L65

**Comment by gschueler** [comment]
Currently the SCM support in rundeck only supports a single job per file. Possibly the SCM Import feature could be modified to allow multiple jobs per file, however it would be more difficult to do that for the SCM Export feature because Jobs are mapped to a file path within the repo based on UUID or name.
