### ISSUE TITLE
Reboot Server Centos/RedHat 7.4 msg error

### ISSUE THREAD

**Issue by charlescoupeau** [rundeck/rundeck#3143]
Issue type: Bug report

When I execute a reboot server on a centos 7.4 or RedHat 7.4 I have an error although the command works.

With Centos 7.4 :

[sudo] password for rundeck:
PolicyKit daemon disconnected from the bus.
We are no longer a registered authentication agent.

With RedHat 7.4:

[sudo] password for rundeck: 
Remote command failed with exit status -1
Failed: NonZeroResultCode: Remote command failed with exit status -1

**My Rundeck detail**

* Rundeck version: 2.10.4-1 
* install type: rpm
* OS Name/version: CentOS 7.4
* DB Type/version: mysql

**Expected Behavior**

**How to Reproduce**

Execute : sudo shutdown -r now (centos7.4) or sudo systemctl reboot

**Comment by mnhan3** [comment]
This isn't a rundeck issue and more of how systemd handles reboot/shutdown.   We notice when ssh-ing into a rel7 box and issuing a reboot/shutdown that the session does not exit with a status 0.    We had to create a wrapper script we called to do the shutdown and exit 0 instead of directly calling sudo shutdown or systemctl reboot.
