### ISSUE TITLE
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[0.0.0.0]}

### ISSUE THREAD

**Issue by sixcorners** [rundeck/rundeck#3249]
Issue type: Bug report/Enhancement Request

![image](https://user-images.githubusercontent.com/585501/38390010-a83af8a8-38e5-11e8-9145-d46831635c43.png)

**My Rundeck detail**

* Rundeck version: Rundeck 2.6.9-1 
* install type: (rpm,deb,war,launcher?) however it's packaged in https://hub.docker.com/r/jordan/rundeck/
* OS Name/version: linux
* DB Type/version: mysql 5.7 aurora

**Expected Behavior**
It's runs a small script.

**How to Reproduce**
I don't know.

Is this supposed to happen? What is it doing? How long is this going to run for?

**Comment by dd5154** [comment]
I have a similar issue with a job referencing another job with a single node specified. If the job runs from cron it fails, if I run it manually, it passes.
NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[server]}

Rundeck 3.0.22-20190512

**Comment by fdevans** [comment]
We apologize if this issue was missed.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
