### ISSUE TITLE
The job is lost, is weird.

### ISSUE THREAD

**Issue by Hackeruncle** [rundeck/rundeck#3321]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.10.7
* install type: (rpm,deb,war,launcher?) war
* OS Name/version:  centos7.3
* DB Type/version: mysql? postgres? h2?..  h2

The job is scheduled  every 3 minutes.
The job is lost in 04:24, is weird.
![job](https://user-images.githubusercontent.com/20901151/39402498-76452e7a-4b93-11e8-97fd-21209437cbfd.png)

**Comment by Wolfram23** [comment]
We have a similar issue that we loose jobs without any error messages or logging. We assume that it could be caused by a high load on the server but are still investigating.

Do you have any news or insights on the issue?

Rundeck version: 2.10.0-1
install type: deb
OS Name/version: Ubuntu 16.04.4
DB Type/version: mysql
