### ISSUE TITLE
GUI Session Timeout disable option

### ISSUE THREAD

**Issue by cwaltherf** [rundeck/rundeck#3519]
Issue type: Enhancement Request

* Rundeck version: all 2.11.4
* install type: (rpm,deb,war,launcher)
* OS Name/version:  all   
* DB Type/version: all

**Expected Behavior**
The default login time to Rundeck GUI is set to 30 minutes and can be increased to 90 minutes.
But an option to disable the session timeout is not available.

**How to Reproduce**
login to Rundeck, start editing something (for example a project or a job) and don't do anything during the next 30 minutes. If you try to retake what you were editing you'll lose the changes due to the session has timed out.

**Comment by epitre** [comment]
To be noted, it seems it is no longer possible to change the session timeout since rundeck 3.0.0 :/ 
https://rundeck.org/docs/history/changelog.html
It would be nice to have the option back

**Comment by hs-hub-world** [comment]
@cwaltherf  @epitre  I know this is not http session timeout but seems like the "rundeck.api.tokens.duration.max=120" in the rundeck-config.properties works for 3.0 web session too -? please give it a try and let us know.

**Comment by epitre** [comment]
@hs-hub-world I don't have a file named rundeck-config.properties :/

**Comment by rlueckl** [comment]
This is a much needed feature. Logging in every 30 minutes is really frustrating, especially with an LDAP backend which requires 2-factor auth. However, when I have the activity page open (which refreshes itself) I won't get logged out.

We definitely need an option to be able to set the timeout freely (for example in `rundeck-config.groovy`). I'd like to set it up to 8-10 hours - log in once in the morning and be done with it for the day.

Rundeck 3.0.12 and 3.0.13

**Comment by sjrd218** [comment]
If you are running Rundeck 3.x you can set the session timeout as follows.
For an 8 hour timeout you could add the following to your rundeck-config.properties:
`server.session.timeout=28800`
You can also set this property using java system properties. For the .deb install you would add a file at: `/etc/default/rundeckd` with the content: ```RDECK_JVM_OPTS="-Dserver.session.timeout=28800"```

Please note if you are running Rundeck in a container such as Tomcat you will need to configure the session timeout in the container instead of using the approach outlined above.

@rlueckl Can you make the modification and let us know if this fixes your issue? Thanks.

**Comment by rlueckl** [comment]
`rundeck-config.properties` was replaced in 2014 (!) with `rundeck-config.groovy` in the Rundeck Puppet Forge module (https://forge.puppet.com/puppet/rundeck).

I don't want to change it to `rundeck-config.properties`, because I wouldn't be able to use the Forge module (without major changes and an own fork).

Putting the property in `rundeck-config.groovy` has no effect. So I'm guessing that the 2 property files are handled differently, which is a shame.

Also, the .deb install doesn't use `/etc/default/rundeckd`! The Debian package doesn't even have this file:

```
root@server ~ # dpkg -L rundeck | grep -i rundeckd
/etc/init/rundeckd.conf
/etc/init.d/rundeckd
root@server ~ # dpkg -L rundeck | grep -i default
root@server ~ # 
```

The init.d script sources `/etc/rundeck/profile`. This is the correct location for **RDECK_JVM_OPTS**. :wink:

@epitre : Depending on your install method you can try putting `RDECK_JVM_OPTS="-Dserver.session.timeout=xxx"` (xxx = timeout in _seconds_) in Rundeck's startup configuration file, which is most likely `/etc/rundeck/profile` or `/etc/default/rundeckd`.

After starting the application you should see the property as a parameter (second to last) of your process:
```
root@server ~ # ps -ef | grep -i rundeck | grep -v $$
rundeck   2678     1  1 07:46 ?        00:00:59 java -Drundeck.jaaslogin=true -Djava.security.auth.login.config=/etc/rundeck/jaas-auth.conf -Dloginmodule.name=authentication -Drdeck.config=/etc/rundeck -Drundeck.server.configDir=/etc/rundeck -Dserver.datastore.path=/var/lib/rundeck/data/rundeck -Drundeck.server.serverDir=/var/lib/rundeck -Drdeck.projects=/var/lib/rundeck/projects -Drdeck.runlogs=/var/lib/rundeck/logs -Drundeck.config.location=/etc/rundeck/rundeck-config.groovy -Djava.io.tmpdir=/tmp/rundeck -Drundeck.server.workDir=/tmp/rundeck -Dserver.http.port=4440 -Xmx4g -Xms4g -Dserver.session.timeout=60 -jar /var/lib/rundeck/bootstrap/rundeck-3.0.13-20190123.war --skipinstall
root@server ~ # 
```
I've used 60 seconds here to test the feature.

**Comment by snhughes** [comment]
It seems that the session doesn't get timed-out in the 'Activity' page.
This is not documented anywhere.
IMHO, we could have the timeout disabled when 'Auto refresh' is selected but enabled when it's not.

**Comment by snhughes** [comment]
I think the thread has drifted from the OP. The user saw the issue in version 2 and I bumped into it too (2.11.10). 
It seems that the session doesn't get timed-out in the 'Activity' page.
This is not documented anywhere and could be considered a security concern.
IMHO, we could have the timeout disabled when 'Auto refresh' is selected but enabled when it's not.
... and of course documented. :)

**Comment by epitre** [comment]
OMG, I'm so sorry, I would like to apologize for 2 things.
1st : as stated by @snhughes , because of me, this thread drifted from its original statement, and I'm sorry about it.
2nd : @rlueckl I haven't replied to your great answer.

I can do nothing for the 1st, so I'll correct the 2nd.

@rlueckl I don't have a `/etc/default/rundeckd` . Do you think I can/should create the file.

Or, should I modify `/etc/rundeck/profile`

Best regards

**Comment by rlueckl** [comment]
Hi @epitre,

in the end I've put the config option in `/etc/rundeck/profile` and it works, so that should be fine.

**Comment by fdevans** [comment]
We apologize if some part of this issue was missed.  Seems there are multiple options above, but if you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team

**Comment by rdoering** [comment]
I updated the profile and rundeck-config.properties without success.

````
ps aux | grep java
rundeck    359 22.6 15.8 10446752 2604920 ?    Sl   09:15  39:43 java -Drundeck.jaaslogin=true -Djava.security.auth.login.config=/etc/rundeck/jaas-loginmodule.conf -Dloginmodule.name=RDpropertyfilelogin -Drdeck.config=/etc/rundeck -Drundeck.server.configDir=/etc/rundeck -Dserver.datastore.path=/var/rundeck/lib/rundeck/data/rundeck -Drundeck.server.serverDir=/var/rundeck/lib/rundeck -Drdeck.projects=/var/rundeck/lib/rundeck/projects -Drdeck.runlogs=/var/rundeck/lib/rundeck/logs -Drundeck.config.location=/etc/rundeck/rundeck-config.properties -Djava.io.tmpdir=/tmp/rundeck -Drundeck.server.workDir=/tmp/rundeck -Dserver.http.port=4440 -Djava.net.preferIPv4Stack=true -Dserver.http.host=127.0.0.1 -Dserver.session.timeout=86400 -Drdeck.base=/var/rundeck/lib/rundeck -Xmx6g -Xms4g -XX:MaxMetaspaceSize=256m -server -jar /var/rundeck/lib/rundeck/bootstrap/rundeck-3.3.1-20200727.war --skipinstall

````

Is there a solution?

**Comment by rlueckl** [comment]
> I updated the profile and rundeck-config.properties without success.
> 
> ```
> ps aux | grep java
> rundeck    359 22.6 15.8 10446752 2604920 ?    Sl   09:15  39:43 java -Drundeck.jaaslogin=true -Djava.security.auth.login.config=/etc/rundeck/jaas-loginmodule.conf -Dloginmodule.name=RDpropertyfilelogin -Drdeck.config=/etc/rundeck -Drundeck.server.configDir=/etc/rundeck -Dserver.datastore.path=/var/rundeck/lib/rundeck/data/rundeck -Drundeck.server.serverDir=/var/rundeck/lib/rundeck -Drdeck.projects=/var/rundeck/lib/rundeck/projects -Drdeck.runlogs=/var/rundeck/lib/rundeck/logs -Drundeck.config.location=/etc/rundeck/rundeck-config.properties -Djava.io.tmpdir=/tmp/rundeck -Drundeck.server.workDir=/tmp/rundeck -Dserver.http.port=4440 -Djava.net.preferIPv4Stack=true -Dserver.http.host=127.0.0.1 -Dserver.session.timeout=86400 -Drdeck.base=/var/rundeck/lib/rundeck -Xmx6g -Xms4g -XX:MaxMetaspaceSize=256m -server -jar /var/rundeck/lib/rundeck/bootstrap/rundeck-3.3.1-20200727.war --skipinstall
> ```
> 
> Is there a solution?

Since Rundeck 3.3.0 the property is called: `server.servlet.session.timeout` ("servlet" added in the middle)

See the upgrade documentation: https://docs.rundeck.com/docs/upgrading/upgrading-to-rundeck-3.3.html#server-session-timeout-property-name-change

**Comment by rdoering** [comment]
Ah, now I get it.

Thanks @rlueckl.

**Comment by Carlos-SS-PMI** [comment]
Sorry, but I've tried all aproximations said here, and my sessions expire always after 30 minutes.
My Rundeck version is 3.3.10.

**Comment by Carlos-SS-PMI** [comment]
> configure the session timeout in the container



> 
> 
> If you are running Rundeck 3.x you can set the session timeout as follows.
> For an 8 hour timeout you could add the following to your rundeck-config.properties:
> `server.session.timeout=28800`
> You can also set this property using java system properties. For the .deb install you would add a file at: `/etc/default/rundeckd` with the content: `RDECK_JVM_OPTS="-Dserver.session.timeout=28800"`
> 
> Please note if you are running Rundeck in a container such as Tomcat you will need to configure the session timeout in the container instead of using the approach outlined above.
> 
> @rlueckl Can you make the modification and let us know if this fixes your issue? Thanks.

How can I configure the session timeout in the Tomcatcontainer?

**Comment by bobhenkel** [comment]
If I put this in my docker-compose.yml file:
`RUNDECK_SERVER_SESSION_TIMEOUT: "43200"`
My /home/rundeck/server/config/rundeck-config.properites contains:
`server.servlet.session.timeout=43200`
instead of the default 3600 value.

I still need to validate this helps with sessions timing out, but I didn't need to do anything fancy to get that value set.

**Comment by bobhenkel** [comment]
Confirmed it works set the value to 30 which is 30 seconds and it was forced out.
