### ISSUE TITLE
rd3 ui: Can't set PASSIVE execution mode from /menu/executionMode

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#3558]

**Comment by sjrd218** [comment]
@jessemarple  This appears to be caused by two subsequent radio divs. Ex. ```<div class="radio">...</div><div class="radio">...</div>``` which causes the non-visible clickable target to be positioned too high instead of right over the circle on the second radio button. So you can click on **PASSIVE** in this case, but you have to hold your mouse way above the circle.

If I put a ```<div>&nbsp;</div>``` between the two divs it fixes the problem, but I don't think that's the right solution. Do you have any ideas about what would make two subsequent radio elements render improperly?

**Comment by jessemarple** [comment]
Looks like the issue is the paragraph of text that had a class of 'col-xs-12' giving it a blocking width inside of it's container and thus pushing up/off the thing below it because that isn't a block level element.
