### ISSUE TITLE
Can I create a job with API？

### ISSUE THREAD

**Issue by X-Mars** [rundeck/rundeck#3756]
I only got help **Importing Jobs** from  [api doc](http://rundeck.org/docs/api/)
My api version is **21**

Thank you very much！

Mars

**Comment by ecarrascos** [comment]
Hi X-Mars,

Indeed, Importing Jobs is the correct way you can create a job with a  Job definition in [either XML or YAML format](http://rundeck.org/docs/api/index.html#importing-jobs) via API. 

You can use "Optional parameters" such as: 

**dupeOption**: A value to indicate the behavior when importing jobs which already exist. Value can be “_skip_”, “_create_”, or “_update_”. Default is “create”.

and

**uuidOption**: Whether to preserve or remove UUIDs from the imported jobs. Allowed values (since V9):

_remove_: Remove the UUIDs from imported jobs. Allows update/create to succeed without conflict on UUID.

Upon import via API to avoid any conflict with pre-existing UUID in the job definition.

Hope it helps!

**Comment by X-Mars** [comment]
Hi ecarrascos,

Thank you my friend. I will have a try.

Mars
