### ISSUE TITLE
Incorrect Long line wrapping for Powershell Inline Script

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#3830]
**Describe the bug**
A job runs a powershell script to get , eg, a user membership.
When the string returned is long, it gets wrapped to two lines in the output console. 
This affects the Key Value Data.

**My Rundeck detail**

* Rundeck version: reported in 2.10.5 , tested in 2.11.5
* install type: any

**To Reproduce**

1. Create job that excutes an Inline Script: 
   Invocation string is "powershell.exe" and file extension is "ps1"

2. Include , eg. , the following inline script: 

```import-module activedirectory
$username = "@option.Username@"
$groups =  (Get-ADPrincipalGroupMembership -Identity $username | Select -expand Name) -join ','
echo $groups
echo "adgroups = $groups"
```
3. Include Key value:

```.
   <LogFilter type='key-value-data'>
        <config>
         <logData>true</logData>
         <regex>^(adgroups)\s*=(.+)\z</regex>
         </config>
   </LogFilter>
```

4. The output is split in 2 lines, capturing an incorrect Key value: 
![image](https://user-images.githubusercontent.com/31705339/44058941-243e6f74-9f26-11e8-8eee-851b2a825adc.png)

**Expected behavior**
The value (when running the script outside Rundeck )  which should be wrapped correctly and captured in Key value: 

![image](https://user-images.githubusercontent.com/31705339/44059007-53a37336-9f26-11e8-85c7-9716cba0554d.png)

**Screenshots**
(see above)

**Comment by eblikstad** [comment]
This is due to the nature of a virtual console which is by default 80 characters wide. You may adjust this using the following command.

$host.UI.RawUI.BufferSize = new-object System.Management.Automation.Host.Size(150,50)

[https://social.technet.microsoft.com/Forums/sharepoint/en-US/7c4d18f2-c52f-4674-b925-27e281f08ac2/how-to-make-the-width-of-powershell-scripts-output-greater-than-80-column](url)
