### ISSUE TITLE
Rundeck 3: jobs view wastes vertical space

### ISSUE THREAD

**Issue by gjvc** [rundeck/rundeck#4021]
**version**
Rundeck 3, jalapeño popper coral camera 2018-08-28, Rundeck 3.0.5-20180828

**Expected behavior**
in the view at, for example, http://myrundeck01.mf:4440/project/my-project/jobs, The job description field should be on the same line as the job name.

**Observed behavior**
The job description field appears beneath the job name, wasting vertical space.

**Comment by Daryes** [comment]
I personally don't mind the description on a second line, given the fact a job's name don't have much length limitation, and it's usual practice to separate the title and the description on different lines.  

On the other hand, having the next occurrence time `in HH:MM` put on the far right side on the same line as the title would be a real gain in space.  
Also, this item should show both the planned time (ie : each day at 6h15 am), AND the remaining time before the execution. Having the information `next in 18h55` doesn't help much for understanding the time of execution on a single glance without having to use the mouse

**Comment by bbomgardner** [comment]
This was also my first impression. Since most of my jobs are in one large project, the new UI unfortunately makes it considerably more difficult to scan through an expanded tree for a particular job. 

A heavier folder name text weight and a more identifiable subfolder design (background, indentation) would also help this view in my opinion.
