### ISSUE TITLE
Allow GIT import to custom branches or use variables to specify branch

### ISSUE THREAD

**Issue by mlamutt** [rundeck/rundeck#4081]
I would like to be able to commit to user defined branch.  On the "Git Export: Commit Changes to Git"  screen add a field to specify the branch that you want to commit to.  You can use the default, that is listed the SCM  configuration, but allow overwriting it.  

In our current SCM process, our developers are used to using a git branch that is labeled the same as the ticket number for the request/bug/project that they are working on.  Being able to use the same branching process would be a great addition to rundeck.

A second approach that would be helpful would be to allow for committing to a branch named for the job name or id:  "Committing to branch: `${job.group}${job.name}"

thanks.

**Comment by SpencerMalone** [comment]
I've started poking at this a bit locally. There are a lot of options here that could be very different. Are you looking to commit and track multiple local branches on rundeck, or just push to an alternative branch on the remote?

**Comment by SpencerMalone** [comment]
Also, your title is about `Allow GIT import`, but I think this is about the git export plugin, right?

**Comment by SpencerMalone** [comment]
I spent this morning poking around, and came up with a rudimentary implementation [here](https://github.com/SpencerMalone/rundeck/tree/git-export-branch-override). After implementing it though, I gave it some more thought, and realized that (at least if you're using public GitHub or GHE), you can do pull requests from tags themselves. Having played around with the workflow, using tags accomplishes what I wanted, just with a slightly different wrapper. Any chance that this workflow fits your environment as well?

**Comment by mlamutt** [comment]
Ill look at using the tags... thanks.

**Comment by kaplanben** [comment]
This issue is very much relevant to us as well.
GitHub doesn't support PRs based on Tags
but even if it did, since the branch is a static string hardcoded in the plugin settings (let's call it `export_branch`) you have the following problem:
1. someone exported Job A and opened a PR (GitHub) so there is a merge request from `export_branch` to `main`
2. someone else exports Job B and wants to open a dedicated PR since the two jobs are not related and should not be on the same PR (for more than one reason).
3. Since the branch is hardcoded and always the same changes related to Job B will automatically be committed and added to the same PR opened on 1 (Job A).

This is not a correct GitOps flow and tags can't help here.
The best option from our POV would have been to support dynamic variables for the branch name in the SCMExportPlugin.
Even create a branch with the same name but suffix it with a timestamp e.g. `export_branch-0601232113` (in our cases we delete the branches after merging).

Any chance this issue can be examined and get attention? My hunch is that this should require a massive change to implement but I may be wrong...
