### ISSUE TITLE
Documentation: Pre-auth mode docs not updated since 2.x

### ISSUE THREAD

**Issue by bluikko** [rundeck/rundeck#4106]
**Describe the bug**
https://rundeck.org/docs/administration/security/authenticating-users.html#preauthenticated-mode still talks about using `web.xml` when using preauthentication mode.

As we all know, the file is gone in 3.x, replaced by what #4060 describes as "You can now programmatically configure the Jetty WebAppContext that Rundeck uses."

And this involves compiling to a JAR? Seriously is this the only way now to do preauth mode? It would be nice if at least the documentation would be updated, since it sounds like a lot of workload installing toolchains and whatnot.

**Expected behavior**
Documentation should have clear instructions how to configure Rundeck for preauth mode in 3.x.

Edit: other solutions I have thought: JAAS Krb5 module, is that supported? I am not very familiar with Java, does this module support something similar to Apache option of "require ldap-filter" to filter the users allowed to authenticate through the module?

**Comment by bluikko** [comment]
I will let you know after the documentation is updated, otherwise I have no idea how to configure it...

**Comment by punshonjm** [comment]
+1 
Having trouble getting this configured due to documentation being outdated.

**Comment by kspear** [comment]
Just want to add my experience.

I've been holding off on migrating to 3.x until I could get pre-authenticated mode working. Despite several attempts, I still end up on the standard Rundeck login page and have to log in against the default realm.properties file, which was not the behaviour in 2.x.

It seems that Rundeck is still trying to authenticate even when "preauthenticated" mode is enabled. This is obviously not the intended or expected behaviour. In 2.x, the solution (as I understood it) was editing the web.xml and removing the auth-constraint, thereby disabling Rundeck's auth mechanism, expecting that an upstream proxy is handling authentication for it. My understanding at the moment is that, without a web.xml (or equivalent config option) where we can disable built-in authentication in Rundeck 3.x, preauthentication does not work at all. If it does work in 3.x (as your comment "using pre-authenticated mode should be even easier" would suggest), the process for doing so successfully is not fully documented anywhere, and so none of us can figure out how to enable it.

If we had a clear example of how to enable preauthenticated mode and have it work as expected in 3.x, as it did in 2.x, that would be incredibly helpful.

**Comment by punshonjm** [comment]
I have had some luck with getting it working. 

In 2.x I didn't have pre-authenticated set up. Part of trying to get it to work I updated to 3.x
In 3.x, all I have done is added the following to _rundeck-config.properties_:

```
rundeck.security.authorization.preauthenticated.enabled = true
rundeck.security.authorization.preauthenticated.userNameHeader=X-Remote-User
rundeck.security.authorization.preauthenticated.userRolesHeader=X-Remote-User-Group
rundeck.security.authorization.preauthenticated.attributeName=REMOTE_USER_GROUPS
rundeck.security.authorization.preauthenticated.delimiter=:
```

This configuration seems to be working great for me.

**Comment by bluikko** [comment]
> ```
> rundeck.security.authorization.preauthenticated.userRolesHeader=X-Remote-User-Group
> rundeck.security.authorization.preauthenticated.attributeName=REMOTE_USER_GROUPS
> rundeck.security.authorization.preauthenticated.delimiter=:
> ```

Just our of curiosity, how do you populate the groups? From LDAP? How?

**Comment by punshonjm** [comment]
I've implemented my own SSO-style solution using nginx and node.js
> nginx acts as reverse proxy for server, server runs both the node.js process (an internal web app & rundeck) 
> nginx passed an auth request to node.js process
> node.js checks token in a cookie and put groups in the header based on what groups that user has in the db (or makes user login), these headers are sent back to nginx
> nginx assigns the headers which are read by RunDeck

**Comment by sjrd218** [comment]
Updated docs here: https://rundeck.org/docs/administration/security/authenticating-users.html#preauthenticated-mode

Please open a new issue if you run into problems getting pre-auth mode working.

**Comment by bluikko** [comment]
It seems the preauth mode configuration in 3.x is indeed more simple than in 2.x. The updated documentation works fine.
