### ISSUE TITLE
project global variables not correctly fetched in Rundeck job options

### ISSUE THREAD

**Issue by cwaltherf** [rundeck/rundeck#4297]
When creating a Global variable, it can be passed and be printed correctly in a node step or an inline script. But if the variable is passed previously to an option variable, the variable doesn't get correctly fetched. It fronts the variable name instead of its value inside a node step or an inline script.

**Comment by ltamaster** [comment]
I think this is fix with https://github.com/rundeck/rundeck/pull/5333

**Comment by fdevans** [comment]
We apologize if this issue was missed.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
