### ISSUE TITLE
Radials and Checkbox Options

### ISSUE THREAD

**Issue by gtsteffaniak** [rundeck/rundeck#4396]
Request for rundeck to support "checkbox" options. Either a single checkbox option, or an option for a row of checkboxes. The checkboxes could be boolean and return the value "True" or "False" if checked.

For example, If I wanted a row of checkboxes, I could create an option "filesCheckbox" checkbox row. With 4 checkboxes in the row, each option could be called with:
$RD_OPTION_CHECKBOX_1
$RD_OPTION_CHECKBOX_2
$RD_OPTION_CHECKBOX_3
$RD_OPTION_CHECKBOX_4

Or radials with the same concept.
![image](https://user-images.githubusercontent.com/42989099/51356244-7bb2e080-1a7f-11e9-96a0-78ba54794e07.png)

**Comment by gschueler** [comment]
You can use "multivalue" feature of options to display checkboxes for multiple values.  The result will be a delimited list of the selected values

**Comment by reinerrdeck** [comment]
I have a good job definition example for that:

```
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option delimiter=',' enforcedvalues='true' multivalued='true' name='Car' required='true' values='audi,bmw,chevy,ford' />
      </options>
    </context>
    <defaultTab>summary</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>569e2386-2f81-4bbf-9a6a-2adc7e042ad8</id>
    <loglevel>INFO</loglevel>
    <name>JobOptions</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo ${option.Car}</exec>
      </command>
    </sequence>
    <uuid>569e2386-2f81-4bbf-9a6a-2adc7e042ad8</uuid>
  </job>
</joblist>
```

**Comment by falloutphil** [comment]
The suggests use of multivalued inputs works, but it's buggy.

If I want to have a checkbox to add a **single** script option eg "--myoption" the only way I can do this is in version 3.0.9-20181127 is to **not** enforce Restrictions.  If I "Enforce from Allowed Values" and only one allowed value exists, then it is automatically ticked and is not untickable.  

If I add a second option, then I can tick either option as you'd expect, and everything then works as you'd expect.  

If I do not enforce Restrictions then because I get the ability to add another value at job run time, so I get the single checkbox I want.  I can then enforce a "Match Regular Expression" to equal "--myoption" so that no other option is possible.

This is a hacky workaround tho - I suspect it's an oversight/bug, and Rundeck should allow the ticking/unticking of a single option enforced from allowed values?

This is easy to reproduce - any chance you could allow ticking of single selection multi-valued options?

**Comment by ahonor** [comment]
👍

**Comment by niall-munnelly** [comment]
Sorry, but why was this closed? It doesn't seem that the original request was addressed:

> Request for rundeck to support "checkbox" options. Either a single checkbox option, or an option for a row of checkboxes. The checkboxes could be boolean and return the value "True" or "False" if checked.

Let's say I have an option that needs to be "True" to kick off a workflow step in my "ruleset" strategy. As it stands in Pro Team 3.0.16, I can force the user to select "True" or "False" with one as a default.  Or I could make the option multivalue, but that just allows me to select both False and True, and not one or the other. Or I could have one allowed value, make the option required, and the execution will use that default value. Or if I have only one allowed value, "True" and make the option "optional," the option will be rendered as a blank field with a dropdown, which is as close as I have gotten to the described behavior.

A simple option name with a checkbox that toggles between false and true on the backend would be a cleaner and more intuitive solution than having an option with a choice of allowed values, eg False, True.

**Comment by falloutphil** [comment]
Agreed - the workaround looks messy, I too hope the feature can be provided in the future.

**Comment by gmcdev** [comment]
A boolean option is definitely needed.

**Comment by DavidMatusik** [comment]
+1, Also have a use case for boolean checkbox
