### ISSUE TITLE
Make privateDataContext available to scripts

### ISSUE THREAD

**Issue by mattqm** [rundeck/rundeck#4425]
**Is your feature request related to a problem? Please describe.**
When using the 'Secure Remote Authentication' input type, it seems there is no way to access this when your node executor is not written in Java.  Choosing the 'Secure' option is not acceptable as the remote nodes will see this in the environment.

**Describe the solution you'd like**
Some sort of CLI to return the privateDataContext that non-Java Node Executors can run so they can access this info.  Maybe a token can be passed as a command line argument, which can then be used to get the data.  Alternatively, is there any reason this data cannot be set as STDIN to the script?

**Describe alternatives you've considered**
I've looked at STDIN, command line args and environment variables.  This 'Secure Remote Authentication' data doesn't appear anywhere.

**Additional context**
There is a bit of a discussion in the rundeck-discuss group: https://groups.google.com/forum/#!topic/rundeck-discuss/0TyR5q9HpzE

**Comment by linuxmail** [comment]
hi,

we have the same problem since we try to figure out, if Rundeck and Ansible is usable. At the moment, it seems to be a PCI DSS blocker.
We had the idea, to submit the SSH key PASSPHRASE to the [SSH-AGENT](https://github.com/Batix/rundeck-ansible-plugin/issues/242), which can used by Ansible. 

I have now a developer and hoping, that he can extend the [Ansible plugin](https://github.com/Batix/rundeck-ansible-plugin) to allow the start the ssh-agent and submit the passphrase., which was entered via "Secure Remote Authentication".

**Comment by linuxmail** [comment]
hi,

is there a way to pay for this function and how much does it cost ?

**Comment by linuxmail** [comment]
hi @mattqm ,

Rundeck would implement that feature for USD 20,000. My company would pay around  USD 5,000. So if we find others for the rest, we can get it into Rundeck.

**Comment by ahonor** [comment]
Hi @linuxmail, We agree that this feature is beneficial to all plugins and are implementing it now.

**Comment by linuxmail** [comment]
hi,

that is really awesome :- ) Thanks so much !
