### ISSUE TITLE
Powershell script doesn't show any output if have Java commands

### ISSUE THREAD

**Issue by reinerrdeck** [rundeck/rundeck#4644]
**Describe the bug**
When execute Java commands on Powershell script on remote Windows box, the output shows blank.

**My Rundeck detail**

* Rundeck version: 3.0.17
* install type: WAR
* OS Name/version: Windows 10 / KDE Neon
* DB Type/version: H2

**To Reproduce**
1. Create this Powershell script:
```
Write-host 'Do Stuff!!'
$command = "java -version"
iex $command
```
Execute locally and works OK (directly or call it from local Rundeck instance)

2. Excecute from remote Rundeck instance and the Java command shows blank.

**Expected behavior**
Java commands must show on output.

**Screenshots**
When executing Powershell script directly on Windows Box:
![Screenshot_local](https://user-images.githubusercontent.com/43051294/54838108-9a636c80-4ca6-11e9-97f8-3b0c9fdb78d3.png)

When call the script using Rundeck on the same Windows Box:
![Screenshot_same_node](https://user-images.githubusercontent.com/43051294/54838113-9d5e5d00-4ca6-11e9-9421-eb74b9af1d6c.png)

When calling the script from remote Rundeck instance pointing to Windows Box:
![Screenshot_remote](https://user-images.githubusercontent.com/43051294/54838122-a0f1e400-4ca6-11e9-9aad-b234c1e7f811.png)

**Additional context**
Related/Origined issue: https://groups.google.com/forum/#!topic/rundeck-discuss/yw7Xoiyr6Gc

**Comment by ltamaster** [comment]
Hi @reinerrdeck ,

It looks similar to this (i think is because of the output redirect )
https://social.technet.microsoft.com/Forums/scriptcenter/en-US/9bc98258-716c-4468-a2a0-6a0c9e6522e6/how-to-avoid-a-powershell-exception-while-retrieving-the-java-version?forum=ITCG

https://stackoverflow.com/questions/2095088/error-when-calling-3rd-party-executable-from-powershell-when-using-an-ide

I got the same error using Powershell ISE
<img width="870" alt="Screenshot 2019-04-10 08 53 11" src="https://user-images.githubusercontent.com/6034968/55880131-15b19300-5b6e-11e9-8be4-24970b50a37d.png">

I found a workaround using Inline Script 

<img width="625" alt="Screenshot 2019-04-10 08 54 27" src="https://user-images.githubusercontent.com/6034968/55880239-48f42200-5b6e-11e9-84f4-fa2cb9deeb1d.png">
<img width="904" alt="Screenshot 2019-04-10 08 54 39" src="https://user-images.githubusercontent.com/6034968/55880240-498cb880-5b6e-11e9-9aa9-ee9423523d27.png">
