### ISSUE TITLE
Running Tab of Job shows nothing initially

### ISSUE THREAD

**Issue by sumpfgottheit** [rundeck/rundeck#4674]
**Describe the bug**
When selecting a Job, the "Activity for this Job" Card seems to have activated the tab "running" but it hasn't. After clicking the "running" tab, the running activities are shown.

**My Rundeck detail**

* Rundeck version: 3.0.17-20190311
* install type: rpm
* OS Name/version: rhel 6.10
* DB Type/version: postgresql 11

**To Reproduce**
1. Go to "Jobs"
2. Click on a Job with a current running activity
3. Scroll down to "Activity for this job"
4. Notice not running activities, although the tab is activated
5. Click on the Tab "running"
6. See the running activities

**Expected behavior**
The running activities are show when selecting the Job, as the tab is activated.

**Screenshots**
![rundeck01](https://user-images.githubusercontent.com/979503/55308186-371dcb00-545a-11e9-9877-85f90fe02c13.png)

![rundeck02](https://user-images.githubusercontent.com/979503/55308192-384ef800-545a-11e9-9428-25eb0228ef45.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version  ESR 52.9

**Additional context**
Maybe releated [issue 4574](https://github.com/rundeck/rundeck/issues/4574) and [4157](https://github.com/rundeck/rundeck/issues/4157)

**Comment by reinerrdeck** [comment]
Hi @sumeshpremraj 

If you don't select "Follow execution" you can see the progress bar.

![01](https://user-images.githubusercontent.com/43051294/55566150-7b66d080-56d1-11e9-8fab-647ab05949a3.png)

![02](https://user-images.githubusercontent.com/43051294/55566877-f2e92f80-56d2-11e9-9631-4a805761c55f.png)

But when you select "Follow execution" at moment fo launch the job, the expected behavior is going to Activity by default. 

![04](https://user-images.githubusercontent.com/43051294/55566965-1ad89300-56d3-11e9-8a8b-0798d56431dc.png)

If you can see the progress you must go to Activity (if you select "Follow execution").

**Comment by sebastianbello** [comment]
+1  
Have the "running " tab auto-refreshed may be the desired option  for some use cases ( a quick check of per-project running jobs )  

An option may be to  have this as "user selectable" via config files.

**Comment by sumeshpremraj** [comment]
@reinerrdeck I believe you wanted to tag @sumpfgottheit 😅
