### ISSUE TITLE
Updating project settings doesn't refresh the settings immediately 

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#4742]
**Describe the bug**
When you save a change on the project settings menu, the changes are not "shown" immediately. Instead, you need to wait (kind of cache) or perform the update twice.
This happens when you store the project settings on the database. 

It seems this PR, in order to avoid deadlocks on storage table, produce the issue.
https://github.com/rundeck/rundeck/pull/4522

**My Rundeck detail**

* Rundeck version: 3.0.20
* install type: launcher
* OS Name/version: MacOs 10.14
* DB Type/version: mysql

**To Reproduce**
1. Go to Edit Configuration
2. Add any change 
3. Save the settings
4. Go again to the Edit Configuration page and you will see the previous version of the settings.

**Expected behavior**
Changes in project settings should be applied it immediately

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser Chrome
 - Version 73

**Comment by fgutierrezz** [comment]
this happens in 3.0.19 , 3.0.21 also

**Comment by DVGeoffrey** [comment]
I am experiencing this problem on 3.0.19

**Comment by gschueler** [comment]
needs backport to 3.0 as well

**Comment by ProTip** [comment]
While reviewing the PR for a fix that didn't involve reverting the changes to fix #4269 introduced in #4522, I ended up reviewing those changes as well and discovered the precise reason(I hope!) it caused the issue we are seeing with the stale project settings. I also believe we should revert those changes and tackle the lock timeout issue separately if it re-appears.
 
PR #4522 introduced a new `withNewTransaction` closure [here](https://github.com/rundeck/rundeck/pull/4522/files#diff-7bf7c6a1d5fb256a3a46a7101cf128cbR290). Unfortunately this has two effects:
1. It bypasses the current hibernate session and transaction, instead opening up a transaction on a new connection. The transaction is not "nested" or piggy-backed onto the current transaction.
2. It caused the return [here](https://github.com/rundeck/rundeck/pull/4522/files#diff-7bf7c6a1d5fb256a3a46a7101cf128cbR313) to be the return for the new closure, not the return for the outer closure. Now `saveStorage` always returns false, and the save occurs again inside a `withSession` also bypassing the current session/transaction.

So after these changes _all_ `saveStorage` calls end up outside the existing session/transaction and the storage, if previously loaded, becomes stale in the outer session.

When saving the project config the project storage manager, after storing the configuration, invalidates the project cache and causes it to reload [here](https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy#L445-L446). My testing shows that even though the database is hit due to using dynamic finders underneath(and it returns the new data becuase we use READ_COMMITTED), hibernate stills returns the object that was loaded into the session earlier.

Because the update was saved out of the current session, the object loaded into the cache is stale. At this point subsequent visits to the edit project settings page will cause the stale object in the project cache to be used to populate the form fields.

There are a few ways I came up with to "make it work", but I suspect the storage service may be the wrong layer to be making decisions about what should and shouldn't be participating in a transaction if we can help it. It would take control of transactional boundaries and participation away from the higher layers, and it may cause nuanced state issues like this one in unexpected places.

**Comment by gschueler** [comment]
closing this issue for 3.1, and opened #4905 to continue the discussion about the reverted fix
