### ISSUE TITLE
ReloadablePropertyFileLoginModule seems to ignore changes to realm.properties

### ISSUE THREAD

**Issue by cyberbliss** [rundeck/rundeck#4763]
**Describe the bug**
ReloadablePropertyFileLoginModule seems to ignore changes to realm.properties made while the Rundeck server is running, i.e. hot reloading doesn't actually occur.

**My Rundeck detail**

* Rundeck version: 3.0.17
* install type: Launcher via Docker image
* OS Name/version: Official Rundeck Docker image
* DB Type/version: in memory version

**To Reproduce**
My jaas-loginmodule.conf config:
```
rundeck {
    org.rundeck.jaas.jetty.ReloadablePropertyFileLoginModule required
        debug="true"
        refreshInterval="5"
        file="/home/rundeck/server/config/realm.properties";


}
```
I believe the problem is that in the ReloadablePropertyFileLoginModule class the refreshInterval of PropertyUserStore is never actually set, so the default of 0 is used. Looking in the source code for PropertyUserStore it seems that 0 actually means the realm.properties file is only read once (the first time there's an authentication request).
Interestingly there is a mechanism to pass in a refreshInterval to ReloadablePropertyFileLoginModule (which is why I tried it) but its never used.
Also, the documentation page https://docs.rundeck.com/docs/administration/security/authenticating-users.html in the section on Hot Reloading is incorrect; the line: `The refresh interval for checking the file is 5 seconds. This is not configurable.`

**Comment by gtsteffaniak** [comment]
You must use the new `hotReload="true"` since 3.0.9

https://github.com/rundeck/rundeck/issues/4268


https://docs.rundeck.com/docs/administration/security/authenticating-users.html
Configuration properties:

hotReload - hotReload="true" enables the ability to modify the user list specified by file without having to restart Rundeck. The refresh interval for checking the file is 5 seconds. This is not configurable.
file - path to a Java Property formatted file in the format defined under realm.properties
