### ISSUE TITLE
Update Available notification does not recognize SNAPSHOT or 3.1.0 is latest release

### ISSUE THREAD

**Issue by skywalke34** [rundeck/rundeck#4789]
**Describe the bug**
Installed Rundeck 3.1.0 Snapshot and the "Rundeck Update Available" notice appears 
**My Rundeck detail**

* Rundeck version: 3.1.0-SNAPSHOT
* install type: Docker
* DB Type/version: mariadb

**To Reproduce**
1. Update to 3.1.0-SNAPSHOT
2. Login
3. View lower left for notification
4. Click on notification

**Expected behavior**
Should not suggest an update is available if running SHAPSHOT or 3.1.0 or above.

**Screenshots**
![image](https://user-images.githubusercontent.com/11443283/57241469-4c07f400-6fee-11e9-9e54-5561ee7aa762.png)
![image](https://user-images.githubusercontent.com/11443283/57241532-693cc280-6fee-11e9-850c-c13e37d2f7bb.png)

**Desktop (please complete the following information):**
 - OS: macOS (running Docker)
 - Browser Chrome

**Comment by fdevans** [comment]
We apologize if this issue was missed.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
