### ISSUE TITLE
Allow empty value on enforced list

### ISSUE THREAD

**Issue by via-justa** [rundeck/rundeck#4901]
**Is your feature request related to a problem? Please describe.**
example issue: #2988

**Describe the solution you'd like**
When creating option list add the option to have an "empty" option
example solution:
 options:
  - delimiter: ','
    enforced: true
    label: Job Tags
    multivalued: true
    allowEmpty: true  <--- add empty value to list
    name: tags
    value: 
    values:
    - val1
    - val2

**Describe alternatives you've considered**
The only alternative for now is *not* enforcing the list and put nothing at the default value

**Comment by fdevans** [comment]
This seems counter intuitive.  Can you explain the use case a bit more?

**Comment by jefferson-rios-globant** [comment]
@fdevans by default the enforced job option list take the first value as default, this is really bad because can induce an user to make a mistake, there is high probability to select a non-desired list value.

**The expect behavior is the following:**
When creating an enforcing list there should exist the option to make the default option blank, so if the user try exec the job with this list value on blank there should be an alert that says **"Option 'XXXX' is required"** same behavior with the list setting **"None Any values can be used"**
