### ISSUE TITLE
OpenSSH file copier "Recursive copy" fails

### ISSUE THREAD

**Issue by binaryfire** [rundeck/rundeck#4983]
**Describe the bug**
Hi all. When using the **openssh / file-copier** and selecting the _Recursive copy_ option for copying files, the step fails with the following message:
`xxxxxx: not a regular file`

The same step works fine with the jsch copier. 

The error message is the same one that SCP throws when trying to copy a directory but forgetting the **-r** flag, so maybe the _Recursive copy_ option isn't being correctly passed to SCP?

**My Rundeck detail**

* Rundeck version: latest
* OS Name/version: ubuntu 18.04
* DB Type/version: mysql

**Comment by ltamaster** [comment]
Hi @menathor 

Can you share your job?
Which version of openssh are you using?

Thanks
Luis

**Comment by ltamaster** [comment]
BTW, did you try adding `-r` 
<img width="648" alt="Screenshot 2019-07-03 11 11 06" src="https://user-images.githubusercontent.com/6034968/60603235-61499680-9d83-11e9-84ca-a4233204a797.png">

**Comment by menathor** [comment]
Hi @ltamaster 

I ended up switching back to jsch because ed25519 keys aren't currently working with openssh either (https://github.com/rundeck/rundeck/issues/4954#issuecomment-502721987). That was the main reason for the switch.

I did try the -r flag but that caused issues with the way paths and wild cards were handled in certain file copy jobs. Sorry I don't have more info to offer atm! All my projects are using jsch now.

Best
