### ISSUE TITLE
Rundeck job running duplicate execute job after SCM from Gitlab

### ISSUE THREAD

**Issue by ekkachai32** [rundeck/rundeck#5037]
**Describe the bug**
When I use SCM to fetch, pull, and import Rundeck job config (.xml) from Gitlab, it's always double triggers the job `One Fail, One Success` on my Rundeck production. I cannot reproduce the issue on my Rundeck docker :(, but the problem is still there on production. Does anyone have any idea where i should check more?

There is no log output on the fail job.
There is no the fail job ID on /var/log/rundeck/rundeck.executions.log

**My Rundeck detail**

* Rundeck version: 3.0.5-20180828
* install type: war
* OS Name/version: Azure ubuntu
* DB Type/version: mssql
* One rundeck instance

<img width="1294" alt="Screen Shot 2562-07-08 at 17 31 40" src="https://user-images.githubusercontent.com/34852301/60804718-538f7900-a1a8-11e9-844f-0601e752c807.png">

![1562582101812](https://user-images.githubusercontent.com/34852301/60804815-98b3ab00-a1a8-11e9-96ff-4225a63421c0.jpg)

**Comment by jtobard** [comment]
@ekkachai32  I am trying to reproduce this issue using gitlab and mssql, without success so far.
To get more info about this, this happens only in one job? If yes, is the only one scheduled?
Do you make the git import via gui or using another tool (rd-cli or api call)?

**Comment by yogeshkumark** [comment]
we also had the similar issue. 
there was 2 trigger at the same minute with different seconds. 
1.	The schedule is * 4/5 ** - meaning runs every 5 minutes, starts on the 4th.  So the job should have been kicked off at 14-JUL-19 01.09.00.000000000 PM instead of 14-JUL-19 01.13.43.000000000 PM.
a.	Question: why didn’t the job kick off at 01.09.00?  What I see here is that it took more than 4 minutes to trigger the job after the expected trigger time.  
Run deck log tells the job kicked off at 01:13:28 UTC (9:13:28 EDT) instead of 1:09.

2.	If the run time takes longer than 5 minutes, the job has an issue.  But I have not seen anything that takes longer 3 minutes and some seconds. 
3.	My expectation is that I should encounter “Previous run incomplete” situations only if run time exceeds 5 minutes, so there is some delay happening in either:

**Comment by jtobard** [comment]
@yogeshkumark your issue was related to SCM using Gitlab too or another git provider for SCM?

**Comment by jessemarple** [comment]
It appears this issue has been abandoned or the the OP has moved on. Our policy is to close issues where no response has been made in 30 days. If you feel as though we have closed this in error or the issue still persists, please reopen the issue.
