### ISSUE TITLE
Problem with job group expansion

### ISSUE THREAD

**Issue by aznkid4ever** [rundeck/rundeck#5119]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 3.1.0
Upgraded to the latest version 3.1.0 today (love the new look and feel by the way). I have job group expansion level in my projects set to 0. 
When I expand one of my initial folders, every single subfolder underneath it is expanding. I have a lot of subfolders underneath the top folder and now after expanding the top folder I have to do a lot of scrollling down.

**Expected Behavior**
In the previous version before upgrading (3.0.24), I wasn't seeing this problem. When I expanded the top folder, every subfolder underneath was still collapsed.

**How to Reproduce**
Upgrade to Rundeck version 3.1.0 and have a top folder with numerous subfolders under it and try to expand that top folder and it will expand every single subfolder underneath.

**Comment by jessemarple** [comment]
@gschueler - I'm stuck with this. In reviewing it, I see that the issue is because a javascript event on the `expandComponentHolder` that toggles `style="display: none"` to `style="display: block"` but I can't seem to find the javascript that triggers that.

Initially, it seems that the sub_group is getting that style set by `style="${wdgt.styleVisible(if: groupopen)}"`

on line 117 of `rundeckapp/grails-app/views/menu/_groupTree.gsp`
