### ISSUE TITLE
Upgrade to 3.1.0 on ubuntu overwrites realm.properties

### ISSUE THREAD

**Issue by menathor** [rundeck/rundeck#5126]
Hi guys,

Just updated rundeck to 3.1.0 on Ubuntu 18.04 using apt update. Unfortunately the update overwrites realm.properties without making any backups. I've manually copied my users from a previous snapshot, however this is something to definitely try and avoid in future updates!

Cheers

**My Rundeck detail**

* Rundeck version: 3.1.0
* OS Name/version: ubuntu 18.04
* DB Type/version: mysql

**Comment by ProTip** [comment]
Hi @menathor ,

Thanks for bringing this to our attention. I have opened a PR on the packaging repo which will hopefully resolve this issue.

For posterity I will add a little context on the issue. We have unified our packaging for the enterprise and oss builds. The goal was to eliminate drift and the maintenance burden of hand syncing changes between two somewhat different packaging projects(Gradle vs Make). Much of the new packaging project was inherited and evolved from the Gradle project and it turns out those file were not marked as conffiles there.

I will release a re-package for `3.1.0` so others do not need to wait for the next Rundeck release.
