### ISSUE TITLE
Failed to read SSH Private key passphrase stored at path

### ISSUE THREAD

**Issue by zychappy** [rundeck/rundeck#5202]
**Describe the bug**
Failed to read SSH Private key passphrase stored at path

**My Rundeck detail**

* Rundeck version: [ 3.1.0-20190731]
* install type: war]
* OS Name/version: [max os 10.14.6 ]
* DB Type/version: [default ]

here is the error message,but the file does exists
```
Failed to read SSH Private key passphrase stored at path: /keys/rundeck/.password: org.rundeck.storage.api.StorageException: Path does not exist: keys/rundeck/.password
--
11:35:34 | Failed: ConfigurationFailure: Failed to read SSH Private key passphrase stored at path: /keys/rundeck/.password
```

**Comment by MegaDrive68k** [comment]
Hi @zychappy 

Check how do you store the pass in key storage for that: go to Gear icon > Key Storage and click on the key (check the "Storage path" string) usually, that happens when the key is wrong referenced on resources.xml file (maybe keys/rundeck/password instead keys/rundeck/.password?)

Kind regards.

**Comment by zychappy** [comment]
@MegaDrive68k Thanks,it works after add a password in key storage,
is it useless the config of project default node executor -->SSH Key Passphrase Storage Path?

**Comment by MegaDrive68k** [comment]
@zychappy 

Even there (Default node executor) you need to reference keys/passwords stored in the key storage.

Cheers!
