### ISSUE TITLE
Ability to Disable AutoComplete on password field of Rundeck login page

### ISSUE THREAD

**Issue by markp80** [rundeck/rundeck#5205]
Our server running Rundeck 3.0.24 is scanned by Qualys Vulnerability scanning and has detected the following vulnerability. Plesse could we have the ability to disable AutoComplete at the application level.

AutoComplete Attribute Not Disabled for Password in Form Based Authentication

THREAT: The Web server allows form based authentication without disabling the AutoComplete feature for the password field. Autocomplete should be turned off for any input that takes sensitive information such as credit card number, CVV2/CVC code, U.S. social security number, etc. 

IMPACT: If the browser is used in a shared computing environment where more than one person may use the browser, then "autocomplete" values may be retrieved or submitted by an unauthorized user. 

SOLUTION: Contact the vendor to have the AutoComplete attribute disabled for the password field in all forms. The AutoComplete attribute should also be disabled for the user ID field. Developers can add the following attribute to the form or input element: autocomplete="off" This attribute prevents the browser from prompting the user to save the populated form values for later reuse. Most browsers no longer honor autocomplete="off" for password input fields. These browsers include Chrome, Firefox, Microsoft Edge, IE, Opera However, there is still an ability to turn off autocomplete through the browser and that is recommended for a shared computing environment. Since the ability to turn autocomplete off for password inputs fields is controlled by the user it is highly recommended for application to enforce strong password rules.

Mark

**Comment by runephilosof** [comment]
I would say Qualys is wrong in this recommendation. Which is an opinion shared by the browser vendors, since they don't honor the autocomplete="off".
Unique passwords and Password Managers is the best practice.
You shouldn't turn off autocompletion just because some users might use a shared os account (and have the browser save the password).
A shared account (such as a library computer) should instead have that browser feature turned off.

It would probably be a good idea to contact Qualys for arguments.
