### ISSUE TITLE
Delete a job after duplicating the job with different UUID. Execution history is not visible anymore

### ISSUE THREAD

**Issue by jervislam0911** [rundeck/rundeck#5238]
**Describe the bug**
Delete a job after duplicating the job with different UUID. 
Execution history is not visible anymore. 

**My Rundeck detail**

* Rundeck version: [ 3.0.22 ]
* install type: [rpm]
* OS Name/version: [e.g. centos 7]
* DB Type/version: [choose: H2]

**To Reproduce**
Delete a job after duplicating the job with different UUID.
Execution history from the deleted job is not visible from GUI 

**Expected behavior**
Still able to see job history from GUI

**Screenshots**
![image](https://user-images.githubusercontent.com/14086195/64749397-82e19f80-d4e3-11e9-9a6b-0bca2cb4881e.png)

**Additional context**
Job history still can be found in /var/lib/rundeck/logs/rundeck. I tried 
1. Import back the old job through scm, job still not visible.
2. Manually move them into the new UUID folder under /var/lib/rundeck/logs/rundeck, still not visible.

**Comment by MegaDrive68k** [comment]
Hi @jervislam0911 

That's happening because the log execution is also deleted with the job. Maybe deserve an enhancement to keep those logs (maybe on a checkbox at the moment of deleting the job).

Also, on 3.1.0 at the moment to expand the execution, the output stucks on "loading".

![Screenshot_1](https://user-images.githubusercontent.com/51376003/65162882-60ceac80-da10-11e9-80cf-cc5a2eac25e0.png)

Thanks for your feedback!

**Comment by javiergoni** [comment]
Is there any update on this? We need to delete some jobs but we can't lose the execution history
Thanks
