### ISSUE TITLE
missing message in activity view for deleting jobs with run later option

### ISSUE THREAD

**Issue by cwaltherf** [rundeck/rundeck#5373]
After clicking on the "Run Later" option for a job, the job will be shown in the activity view.
Going to the bulk edit option in the activity view having selected this job, the "delete" option will be available for this job execution, "Delete Selected Executions". After clicking on this option and confirming the action to delete the activity for this job, it can't be deleted and a message appears showing 2 brackets "{}" instead of a message that states that the activity can't be deleted due to the job hasn't run yet. 

![run_later](https://user-images.githubusercontent.com/36487101/66599888-a5b2b280-eb7a-11e9-92ce-2a95b95a3ec5.png)

![error_message](https://user-images.githubusercontent.com/36487101/66599749-5cfaf980-eb7a-11e9-80c9-4ec3411b9c01.png)

**Comment by jtobard** [comment]
Different error on 3.2.0-SNAPSHOT but still a bug:
![image](https://user-images.githubusercontent.com/2894508/66654214-1c4dbf80-ec10-11e9-94fc-b587bf818fae.png)

**Comment by gschueler** [comment]
The delete request should have a better error result if there is a running/scheduled execution in the IDs, and the GUI should display that correctly.

However, a fix should also make it so that the Activity View page should not allow a running/scheduled execution to be selected for the bulk delete as well.
