### ISSUE TITLE
Database warnings when upgrading to mariadb 10.3

### ISSUE THREAD

**Issue by dd5154** [rundeck/rundeck#5416]
**Describe the bug**
Database warnings when upgrading to mariadb 10.3.

"mysqld: [Warning] InnoDB: Cannot add field `jc_exec_id` in table `rundeck`.`base_report` because after adding it, the row size is 8381 which is greater than maximum allowed size (8126) for a record on index leaf page."

This error occurs for 15 fields

* Rundeck version: 3.1.2.20190927-1
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: mariadb/mysql

**To Reproduce**
1. Upgrade to maridb 10.2, then 10.3 from 10.1
2. start mariadb
3. run mysql upgrade

**Expected behavior**
I did this on my test server and the error doesn't show up on production

**Comment by MegaDrive68k** [comment]
Hi @dd5154 

I see the same behavior following this to reproduce:

1) Under MariaDB 10.1 generate the Rundeck database.
2) `systemctl stop mariadb`
3) Upgrade MariaDB to 10.2 (or 10.3/10.4)
4) `systemctl start mariadb`
4) Run `mysql_upgrade -u root -p`
5) Check the mariadb log with `journalctl -u mariadb` or `journalctl | grep "Warning"`

And see the following warnings (i my case):

Oct 25 12:26:51 centos7.localdomain mysqld[3086]: 2019-10-25 12:26:51 140662099920640 [Warning] InnoDB: Cannot add field `node_include_name` in table `rundeck`.`execution` because after adding it, the row size is 8754 which is greater than maximum allowed size (8126) for a record on index leaf page.

Oct 25 12:27:46 centos7.localdomain mysqld[3086]: 2019-10-25 12:27:46 140662662530816 [Warning] InnoDB: Cannot add field `adhoc_script` in table `rundeck`.`base_report` because after adding it, the row size is 8631 which is greater than maximum allowed size (8126) for a record on index leaf page.

Oct 25 12:27:46 centos7.localdomain mysqld[3086]: 2019-10-25 12:27:46 140662662530816 [Warning] InnoDB: Cannot add field `node_include_tags` in table `rundeck`.`node_filter` because after adding it, the row size is 8728 which is greater than maximum allowed size (8126) for a record on index leaf page.

Oct 25 12:27:46 centos7.localdomain mysqld[3086]: 2019-10-25 12:27:46 140662662530816 [Warning] InnoDB: Cannot add field `filter` in table `rundeck`.`scheduled_execution` because after adding it, the row size is 8726 which is greater than maximum allowed size (8126) for a record on index leaf page.

Oct 25 12:27:46 centos7.localdomain mysqld[3086]: 2019-10-25 12:27:46 140662662530816 [Warning] InnoDB: Cannot add field `file_extension` in table `rundeck`.`workflow_step` because after adding it, the row size is 8215 which is greater than maximum allowed size (8126) for a record on index leaf page.

Seems a MariaDB bug:

https://jira.mariadb.org/browse/MDEV-19292

Screenshot:

![Screenshot_3](https://user-images.githubusercontent.com/51376003/67574687-4b385b00-f711-11e9-8d72-cf06c2554038.png)

Regards!

**Comment by dd5154** [comment]
Changing strict mode to off didn't remove the errors.

**Comment by dd5154** [comment]
Looks like the issue is resolved when I upgraded to rundeck 3.2.1
