### ISSUE TITLE
No project folder exists, after created a project

### ISSUE THREAD

**Issue by lcgogo** [rundeck/rundeck#5802]
**Describe the bug**
No project folder exists, after created a project

**My Rundeck detail**
yum install in CentOS 7.3

**To Reproduce**
1. install rundeck
2. create a project named mytest
3. no project folder under default project folder: /var/lib/rundeck/projects

[root@izj6cc31t0jo4vu4i9pxc9z projects]# pwd
/var/lib/rundeck/projects
[root@izj6cc31t0jo4vu4i9pxc9z projects]# ls
[root@izj6cc31t0jo4vu4i9pxc9z projects]#

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by lcgogo** [comment]
I can find the cache folder and log folder
[root@izj6cc31t0jo4vu4i9pxc9z projects]# cd /
[root@izj6cc31t0jo4vu4i9pxc9z /]# find ./ -name mytest
./var/lib/rundeck/var/resourceModelSourceCache/mytest
./var/lib/rundeck/logs/rundeck/mytest

**Comment by MegaDrive68k** [comment]
Hi @lcgogo 

That's because the projects are stored in the H2 database by default (not in the filesystem). You can check that in your` /etc/rundeck/rundeck-config.properties` file. 

`rundeck.projectsStorageType=db`

The main advice is to configure your Rundeck instance with a "real" database like MySQL or PostgreSQL, you can check that here:

https://docs.rundeck.com/docs/administration/configuration/database/

Hope it helps!

**Comment by lcgogo** [comment]
> 
> 
> Hi @lcgogo
> 
> That's because the projects are stored in the H2 database by default (not in the filesystem). You can check that in your` /etc/rundeck/rundeck-config.properties` file.
> 
> This line:
> 
> `rundeck.projectsStorageType=db`
> 
> The main advice is to configure your Rundeck instance with a "real" database like MySQL or PostgreSQL, you can check that here:
> 
> https://docs.rundeck.com/docs/administration/configuration/database/
> 
> Hope it helps!

Many thanks! Will try to config a mysql to test.
