### ISSUE TITLE
Make the "required role" in web.xml configurable

### ISSUE THREAD

**Issue by diranged** [rundeck/rundeck#590]
The "role" thats required to exist on all users who log into Rundeck should be configurable, rather than being hard-coded to "user". Frankly, it should also be optional...

**Comment by ava-dylang** [comment]
Can this role requirement be turned off entirely?

**Comment by ssbarnea** [comment]
:+1: Any news on this? After 2 days, I am still unable to finish the LDAP configuration step, which usually takes only few minutes on other services.

**Comment by joerocklin** [comment]
Getting ready to do an update, remembered that I had an unexpected downtime after the last one, found this issue to remind me what to do. We're approaching the 2-year mark on this issue, any news on the state of things?

**Comment by gschueler** [comment]
@joerocklin good question, the status of this issue is: we don't have any immediate plans for a "fix".  

Reasons:

1. making this "configurable" requires rewriting the `web.xml` prior to the webapp starting up.  Not an ideal fix, and especially hard to do in the case of a .war deployment anyway
2. Whether you are using Jetty (e.g. via the Launcher or with the default RPM install) or Tomcat, there is already a workaround via configuration:
    * the JettyCachingLdapLoginModule (JAAS module used for Jetty) supports a `supplementalRoles` setting, that allows you add "user" to the default roles for any successfully authenticated user.  See [Login module configuration](http://rundeck.org/docs/administration/authenticating-users.html#login-module-configuration)
    * The JNDIRealm (realm module used for Tomcat) authentication also supports a `commonRole` setting to do a similar thing for a single role name, see [JNDIRealm#commonRole](https://tomcat.apache.org/tomcat-7.0-doc/api/org/apache/catalina/realm/JNDIRealm.html#commonRole)
3. because of limitations of "servlet-container based authentication", we hope that at some future point we can move to something more flexible

**Comment by xeor** [comment]
Did this discussion die out again? It would be nice to get a better error message when you don't have access to rundeck. The roles rundeck is able to see in my setup is also everything except the `Domain Users` group, so I am stuck with adding a bunch of roles to my `web.xml` to try to catch all users.

The message you get about not having access to any projects is by far good enough as a default `access denied` message. So the option in my configuration am looking for is just a way to set the accepted role to `*` (which doesn't work btw)..

**Comment by DerfOh** [comment]
+1 Being able to set ACL based on the AD group needs better documentation. I've been at this for a week now :cry:

**Comment by zonArt** [comment]
+1 for better documentation, supplementalRoles option works great but you should be aware that you need to put "user, <other_groups>".
If you only put the other_groups it doesn't work, as the param is called **supplemental**Roles, I was expecting user to be integrated already

**Comment by sjrd218** [comment]
Fixed in Rundeck 3.0.0

**Comment by Bigd271** [comment]
Agreed, @sjrd218 please comment on how to use the new "fix"

**Comment by sjrd218** [comment]
Rundeck 3.x is built on top of Grails 3.x which removed the web.xml file altogether from the deployment artifact. This means there won't be a web.xml file you can edit. 

Additionally Rundeck 3.x now uses Spring Security to secure the application. With this change there is no longer a 'required role' that must be configured for Rundeck. 

If you were previously using the tomcat-users.xml file to manage users, you will want to migrate to use one of the JAAS options documented here: https://rundeck.org/docs/administration/security/authenticating-users.html#jetty-and-jaas-authentication. You can ignore the fact that it is labeled 'Jetty and JAAS authentication' because JAAS authentication will work for any container.
