### ISSUE TITLE
Error handler for time out job 

### ISSUE THREAD

**Issue by eligosfx** [rundeck/rundeck#6008]
Please provide an error handler for time out a job like a steps

**Comment by MegaDrive68k** [comment]
Hi @eligosfx 

You can set a [timeout](https://docs.rundeck.com/docs/manual/creating-jobs.html#creating-a-job) on your job (for that, edit your job an go to the "Others" tab and set the time on "Timeout" textbox), with this any timeout is considered as error for your [Error Handler](https://docs.rundeck.com/docs/manual/job-workflows.html#error-handlers).

![Screenshot_3](https://user-images.githubusercontent.com/51376003/81226421-d47df380-8fb8-11ea-81a2-5ecb2ecab5ea.png)

If the job takes less of 3 seconds to be done:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/81226315-ab5d6300-8fb8-11ea-831a-20a9b59297a3.png)

If the job takes more of 3 seconds to be done (the Error Handler is triggered):

![Screenshot_2](https://user-images.githubusercontent.com/51376003/81226581-0db66380-8fb9-11ea-8729-673234d7ee96.png)

I leave an example with an intentional timeout to test (timeout: 3 seconds and the jobs take 5 seconds to run).

```xml
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>75d39c31-cefa-4a46-a89b-01aa2218ca4d</id>
    <loglevel>INFO</loglevel>
    <name>JobTIMEOUT</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <errorhandler>
          <exec>echo "timeout!"</exec>
        </errorhandler>
        <exec>sleep 5; echo hi</exec>
      </command>
    </sequence>
    <timeout>3s</timeout>
    <uuid>75d39c31-cefa-4a46-a89b-01aa2218ca4d</uuid>
  </job>
</joblist>
```

Hope it helps!
