### ISSUE TITLE
Unable to see Active Jobs under Activity TAB

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6020]
in the previous versions of Rundeck we were able to see any active jobs from the job page. It seems we are not longer able to see any "active" jobs from the Activity TAB.

RUNDECK
APIVERSION : 35
BASE : /var/lib/rundeck
BUILD : 3.2.5-20200403
BUILDGIT : v3.2.5-0-g31c833d
VERSION : 3.2.5-20200403
ARCH : amd64
NAME : Linux
VERSION : 3.10.0-862.14.4.el7.x86_64
IMPLEMENTATIONVERSION : 25.212-b04
NAME : OpenJDK 64-Bit Server VM
VENDOR : Oracle Corporation
VERSION : 1.8.0_212

![image](https://user-images.githubusercontent.com/20629911/80979533-4ea55100-8ddc-11ea-9f6b-8bd6ede27a01.png)

Thank you!
HS

**Comment by MegaDrive68k** [comment]
Hi @hs-hub-world 

I think that is expected behavior, the default screen that you're seeing is the current execution screen (and you can see the current execution it on the up of the screen).

For example, if you click on the job (from the job list) you can see the current execution:

![Screenshot_5](https://user-images.githubusercontent.com/51376003/102790823-d13b4a80-4384-11eb-8196-454630a1359a.png)
