### ISSUE TITLE
In pre-auth mode, Rundeck ignores roles from the header in RuleEvaluator

### ISSUE THREAD

**Issue by leshik** [rundeck/rundeck#6070]
**Describe the bug**

With pre-auth mode configured, Rundeck ignores roles passed through the header in  RuleEvaluator despite the fact it "knows" them.

**My Rundeck detail**

* Rundeck version: 3.2.6
* install type: Docker official
* DB Type/version: any

**To Reproduce**

From `rundeck-config.properties`:

```
rundeck.security.authorization.preauthenticated.enabled=true
rundeck.security.authorization.preauthenticated.attributeName=REMOTE_USER_GROUPS
rundeck.security.authorization.preauthenticated.delimiter=,
rundeck.security.authorization.preauthenticated.userNameHeader=X-Forwarded-User
rundeck.security.authorization.preauthenticated.userRolesHeader=X-Forwarded-Roles
```

Headers passed:

```
X-Forwarded-User: leshik
X-Forwarded-Roles: admin,user
```

Proof it gets them (`/user/profile`):

![image](https://user-images.githubusercontent.com/443678/82197058-b43d2580-9924-11ea-8ec1-295d83a0b123.png)

Logs:

```
[2020-05-18 09:18:30,590] WARN  authorization.RuleEvaluator RuleEvaluator - Evaluating Decision for: res<name:Test, type:project> subject<Username:leshik Group:user> action<delete_execution> env<rundeck:auth:env:application:rundeck>: authorized: false:  No context matches subject or environment => REJECTED_NO_SUBJECT_OR_ENV_FOUND (0ms)
[2020-05-18 09:18:30,594] WARN  authorization.RuleEvaluator RuleEvaluator - Evaluating Decision for: res<name:Test, type:project> subject<Username:leshik Group:user> action<admin> env<rundeck:auth:env:application:rundeck>: authorized: false:  No context matches subject or environment => REJECTED_NO_SUBJECT_OR_ENV_FOUND (0ms)
```

**Expected behavior**

RuleEvaluator should evaluate all groups, not only `user`.

**Comment by leshik** [comment]
Hey @gschueler – what's wrong might be with that?
I can't delete executions, for example:

![image](https://user-images.githubusercontent.com/443678/84371662-31964600-ac04-11ea-84a9-0cf9f21bcc83.png)

I believe that's a pretty serious issue.

**Comment by leshik** [comment]
@tlots maybe you could give some clues? Any help is really appreciated.

**Comment by tlots** [comment]
Hello @leshik,

I apologize for the delay. I seem to have missed the notification. 

"Rundeck ignores roles passed through the header in RuleEvaluator despite the fact it "knows" them."

This does seem like something worth fixing. 

It's been a few years since I worked on the original pre-auth functionality and I'm not up to speed on what changes have happened around this. I see your issue #6337 may also be related. 

It is uncertain if I will be able to find the time to dig in to this more, my initial piece of work was part of a client's infrastructure improvement that we decided to contribute. I have been largely uninvolved with Rundeck since then.

John

**Comment by leshik** [comment]
Turns out, the issue was in my setup, which I described [here](https://github.com/rundeck/rundeck/issues/5656#issuecomment-621059856). I whitelisted the whole `^/api/` to make webhooks work, but this made some XMLHttpRequests unauthenticated. I'll edit that post.
