### ISSUE TITLE
Job unschedule with multiple selection have effect only on 1st selected item 

### ISSUE THREAD

**Issue by PeterGarlic** [rundeck/rundeck#6121]
**Describe the bug**
Disabled schedule on multiple selection doesn't work.

**My Rundeck detail**

* Rundeck version: 3.2.8
* Install type: rpm
* OS Name/version CentOS 7.8
* DB Type/version: mysql

**To Reproduce**
1. Go to 'Projects->jobs'
2. Click on 'Job actions->disable schedule'
3. Press ESC: multiple selection is now available. 
4. Select more than on job,  Click on 'Job actions->disable schedule'
5. A popup window ask for "Disable schedules for all selected Jobs?"
6. Only the first job on selected items will be changed.

**Expected behavior**
All the selected jobs must be changed. 
Same issue for other operations on multiple selection.

**Desktop (please complete the following information):**
 - OS: Windows 10 / Fedora 32
 - Browser: Firefox
 - Version: 77.0.1 / 76.0.1

**Comment by MegaDrive68k** [comment]
Hi @PeterGarlic 

I followed your steps and I saw the same behavior, but I think that is expected behavior because we're selecting the individual job action button (in fact, following your steps I understand that you're clicking on "Action" button from the right), to apply the bulk action, on step 4, click on "Perform Action" button and later on "Disable Schedule".

![Screenshot_1](https://user-images.githubusercontent.com/51376003/84937087-3b5af600-b0a9-11ea-87d6-ae242353823c.png)

![Screenshot_2](https://user-images.githubusercontent.com/51376003/84937089-3c8c2300-b0a9-11ea-9f4e-eb69e3a0bdf6.png)

Greetings!
