### ISSUE TITLE
Error 500 after set project.disable.schedule and/or project.disable.executions on project.properties (3.3.0-PREVIEW2)

### ISSUE THREAD

**Issue by MegaDrive68k** [rundeck/rundeck#6139]
**Describe the bug**

At the moment of set `project.disable.schedule` or `project.disable.executions`on project.properties configuration Rundeck shows an Error 500.

**My Rundeck detail**

* Rundeck version: 3.3.0-PREVIEW2
* install type: WAR
* OS Name/version: Ubuntu 20.04
* DB Type/version: H2

**To Reproduce**

1. Go to Project Settings > Edit Configuration > Edit Configuration File (up to right button).
2. Set `project.disable.schedule=true` or `project.disable.schedule=false` and save it.
3. See error.

**Screenshots**

![Screenshot_1](https://user-images.githubusercontent.com/51376003/84709548-61a95600-af30-11ea-8d37-f2211a095dfe.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox 77.0.1.

**Additional context**
Also happens with `project.disable.executions=true` or `project.disable.executions=false`

Full error stack trace: [error500.txt](https://github.com/rundeck/rundeck/files/4783160/error500.txt)

**Comment by gschueler** [comment]
this error is occurring because a method call has the wrong number of arguments. it seems this has been an error since 2017, https://github.com/rundeck/rundeck/commit/10b51edc9de9c1a24505421a6ae55a27271f9de4#diff-1bc46973d157a45ecafb25337c80a183R1200

this only occurs if you manually add the property in the project properties editor, but does not affect the simple GUI toggle method.
