### ISSUE TITLE
Handle login failures in Rundeck log as warning instead of stack trace

### ISSUE THREAD

**Issue by mazzella-c** [rundeck/rundeck#6146]
**Is your feature request related to a problem? Please describe.**
When a user mistypes its password at login it generates a huge stack trace which is not relevant in most cases.

**Describe the solution you'd like**
Possibility to replace stack trace by warning

**Comment by sjrd218** [comment]
We set the default logging level for the grails security classes that handle authentication to DEBUG, so that users would have the ability to see when log in failures occur. 

If you want to repress these messages you can change the logging level for the `grails.plugin.springsecurity.web.authentication.GrailsUsernamePasswordAuthenticationFilter` to INFO and you won't see the stacktrace anymore.

In Rundeck 3.3.x you can change the log level for the `grails.plugin.springsecurity.web.authentication.GrailsUsernamePasswordAuthenticationFilter` logger to INFO in the log4j2.properties file.

In Rundeck 3.2.x and below you can add a rundeck-config.groovy in your server configuration directory with these contents:

```
import org.slf4j.LoggerFactory
import ch.qos.logback.classic.LoggerContext
import ch.qos.logback.classic.Level

LoggerContext loggerContext = (LoggerContext)LoggerFactory.getILoggerFactory();
loggerContext.getLogger("grails.plugin.springsecurity.web.authentication.GrailsUsernamePasswordAuthenticationFilter").setLevel(Level.INFO)
```
