### ISSUE TITLE
Scheduled job using option with remote URL won't run

### ISSUE THREAD

**Issue by kfkonrad** [rundeck/rundeck#6207]
**Describe the bug**
When I schedule a job that uses an option with a remote URL, this job is never executed at the scheduled time. When I execute the job manually or use "Run Job Later" the job is executed as expected.

**My Rundeck detail**
* Rundeck version: 3.2.8.20200608-1
* install type: deb
* OS Name/version: Debian GNU/Linux 10.0.0 _Buster_
* DB Type/version:postgres

**To Reproduce**
1. Set up any Job with an option that uses a remote URL
2. Set a schedule for that job
3. Wait until the job is scheduled
4. See that the job wasn't executed and doesn't show up in Activity.
5. Check the `service.log` to see errors similar to these: https://gist.github.com/kfkonrad/5771a91c9e7b971115c4869b63543904

**Expected behavior**
The job should be executed, logged and visible in the Activity area.

**Desktop**
 - OS: Windows 10 1903
 - Browser: Firefox
 - Version: 77.0

**Comment by christi3k** [comment]
We also encounter this issue as noted in #5810

**Comment by gkranis** [comment]
We are also having this problem.
We upgraded to latest (`3.3.2-20200817`) seeing that it contained https://github.com/rundeck/rundeck/pull/5041. Looks like it regressed in the meantime
It doesn't seem to work no matter what. Playing with permutations of the  `Required` or `Default value` fields of the respective option does not make a difference.
Not sure if issue #5810 is related, it specifically mentions options with `Required: true` while this issue is more generic
