### ISSUE TITLE
How do I view large logs -?

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6223]
Just upgraded to the latest version and it seems I can't view large logs any more..

![image](https://user-images.githubusercontent.com/20629911/86741811-869f5f00-bfec-11ea-8939-0a9f1fd41491.png)

RUNDECK
APIVERSION : 35
BASE : /var/lib/rundeck
BUILD : 3.3.0-20200701
BUILDGIT : v3.3.0-0-g66e3ef7
SERVERUUID :
VERSION : 3.3.0-20200701

Thank you,
HS

**Comment by MegaDrive68k** [comment]
Hi @hs-hub-world 

Right now, you can download the log or enable the legacy viewer, for that add this line to your rundeck-config.properties file: 

`rundeck.feature.legacyExecOutputViewer.enabled=true`

And restart your instance.

Now you can see the output like 3.2.X:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/86802629-356e8a00-c043-11ea-95fc-1aa27a75960f.png)

Regards!

**Comment by hs-hub-world** [comment]
@MegaDrive68k Thanks, that works.

**Comment by ProTip** [comment]
Hi @hs-hub-world ,

We were noticing that the legacy viewer was having trouble loading even a 1.4Mb file of 22k lines; it could take well over a minute or more to finish loading. The new viewer can easily handle this now, however we are still working out a strategy to handle very large logs for the future.

- In order to collect more information I was hoping you could share information about your experience your 29.3Mb log file:
- About how many lines actually get rendered from this?
- Does the legacy viewer finish loading this?
- If so, and if not, how long does the legacy viewer take to load the log?

Thanks!
