### ISSUE TITLE
Webhook Notifications to Google Chat not working. 

### ISSUE THREAD

**Issue by eelbrink** [rundeck/rundeck#6351]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: **3.3.1**
* install type: **rpm**
* OS Name/version: **CentOS Linux release 8.2.2004 (Core)**
* DB Type/version: **h2**

**Expected Behavior**
I am trying to make use of Google Chat Webhooks to receive notifications from Rundeck into a Google Chat Group. The correct behavior would be that when i execute a rundeck job, that i get notified accordingly. 

**How to Reproduce**
Using Google Chat, setup a webhook within a Google Chat Group - https://developers.google.com/hangouts/chat/how-tos/webhooks

**Error Messages**

`[2020-08-06T22:16:29,173] ERROR services.NotificationService - Notification failed [onsuccess,succeeded,81]; URL https://chat.googleapis.com/v1/spaces/*************************************************: Unable to POST notification after 1 tries: success for execution 81 (succeeded): server response: 400 Bad Request`

It seems to be complaining about a 400 `Bad Request` which seems like Rundeck is not sending the correct request type to the GoogleChat API. However when i do a webhook call using curl or python scripts, it works fine.

**Comment by sjrd218** [comment]
When you post to the Google chat api with curl what is the message body you are sending the api?

**Comment by eelbrink** [comment]
Hi Stephen,     

`curl -X POST -H 'Content-Type: application/json' 'https://chat.googleapis.com/v1/spaces/*******/messages?key=*************&token=***************' -d '{"text": "hello world!"}'    `

Kind Regards  
Eddy

**Comment by sjrd218** [comment]
Based on the information from this page: https://developers.google.com/hangouts/chat/reference/message-formats I would guess that Google is sending you a 400 because it does not understand the information Rundeck is sending it. Rundeck is not sending the execution information in a format that conforms to the Google message format. 

You might try creating your own notification plugin to take the execution information from Rundeck and format it into one of Google's message formats. If you create your own plugin, please consider sharing it with the rest of the Rundeck community. Thanks!
