### ISSUE TITLE
Rundeck 2.0: Java error mesage displayed in job output

### ISSUE THREAD

**Issue by goodwillcoding** [rundeck/rundeck#648]
This case is reproduced due to incorrect ssh key, but the bug is that Java Error Message is showing in the output.
1. Setup a project with ssh private that key was password protected
2. Run any ad-hoc job against any node so the key would be used
3. Run job

Witness Java Error Message:

```
17:11:46 test_server Authentication failure connecting to node: "test_server". Make sure your resource definitions and credentials are up to date.
17:11:46             Failed: AuthenticationFailure: Authentication failure connecting to node: "test_server". Make sure your resource definitions and credentials are up to date.
17:11:46 rundecksrv  Execution failed: 13: [Workflow step failures: {1=Dispatch failed on 1 nodes: [test_server: AuthenticationFailure: Authentication failure connecting to node: "test_server". Make sure your resource definitions and credentials are up to date.]}, Node failures: {test_server=[AuthenticationFailure: Authentication failure connecting to node: "test_server". Make sure your resource definitions and credentials are up to date.]}]
```

Expected:

Not sure. Maybe reference to check in error log?
The problem is really that the error message can give out sensitive information (though it did not in this case.

**Comment by ssbarnea** [comment]
Clearly this is an important bug. We switched one of the nodes which means that this could be caused by the server key signature change or because the public key is not installed on the new machine. Still there is no way to tell this from this line and I see no reason for not having a proper error message, one that would indicate you what you have to do to fix it.

**Comment by gschueler** [comment]
the message `Authentication failure connecting to node: "test_server". Make sure your resource definitions and credentials are up to date.` is printed when SSH fails specifically due to authentication not succeededing... It's not really possible to tell what is the cause of that problem (bad password, bad private key, bad private key passphrase, bad key good passphrase, etc.).

we could possible echo additional information about what kind of authentication was attempted, that could be useful.

**Comment by ssbarnea** [comment]
I don't know what approach are you using while trying to connect via ssh, but I know that the ssh client does gives different messages, and also is able to give more information using `-vv` switches. I didn't try but probably even the return code is different for each kind of error.
