### ISSUE TITLE
Some workflow steps are missing from Node view 

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6772]
Hi, I am not sure if this is by design but not all workflow steps are shown in the "Node" view section.
Fore example, the screenshot below shows the HTTP request step.
 
![image](https://user-images.githubusercontent.com/20629911/107393088-3707a100-6aaf-11eb-8d6d-dfa5c11fcdbf.png)

Rundeck Version:

![image](https://user-images.githubusercontent.com/20629911/107393292-7df59680-6aaf-11eb-91cb-9161f2f04724.png)

Thank you,
HS

**Comment by MegaDrive68k** [comment]
Hi @hs-hub-world,

Could you share a basic job definition example to test it?

I've tested with this one:

```xml
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>13ddd164-b981-4258-82b1-1b23c2cd8087</id>
    <loglevel>INFO</loglevel>
    <name>HelloWorld</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "step one"</exec>
      </command>
      <command>
        <step-plugin type='edu.ohio.ais.rundeck.HttpWorkflowStepPlugin'>
          <configuration>
            <entry key='authentication' value='None' />
            <entry key='checkResponseCode' value='true' />
            <entry key='method' value='POST' />
            <entry key='printResponse' value='true' />
            <entry key='printResponseToFile' value='false' />
            <entry key='proxySettings' value='false' />
            <entry key='remoteUrl' value='https://httpbin.org/anything' />
            <entry key='sslVerify' value='false' />
            <entry key='timeout' value='30000' />
          </configuration>
        </step-plugin>
      </command>
      <command>
        <exec>echo "step three"</exec>
      </command>
    </sequence>
    <uuid>13ddd164-b981-4258-82b1-1b23c2cd8087</uuid>
  </job>
</joblist>
```

![Untitled](https://user-images.githubusercontent.com/51376003/107512510-b4054a00-6b85-11eb-92cc-c47a50a99e41.png)

Thanks!

**Comment by gaddman** [comment]
@MegaDrive68k your example is running locally rather than dispatching to nodes. Here's an example where it is dispatching to nodes (filtering on `tags: testnodes` but use whatever is appropriate). It uses the [*nixy Local Steps](https://resources.rundeck.com/plugins/nixy-local-steps/) plugin, but any workflow step will do. 

```xml
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description>Illustrate that workflow steps don't show in the node view</description>
    <dispatch>
      <excludePrecedence>true</excludePrecedence>
      <keepgoing>true</keepgoing>
      <rankOrder>ascending</rankOrder>
      <successOnEmptyNodeFilter>false</successOnEmptyNodeFilter>
      <threadcount>1</threadcount>
    </dispatch>
    <executionEnabled>true</executionEnabled>
    <id>13ddd164-b981-4258-82b1-1b23c2cd8087</id>
    <loglevel>INFO</loglevel>
    <name>workflow and node steps</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <nodefilters>
      <filter>tags: testnodes</filter>
    </nodefilters>
    <nodesSelectedByDefault>true</nodesSelectedByDefault>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <schedules />
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <description>step one: node</description>
        <exec>echo "step one"</exec>
      </command>
      <command>
        <description>step two: workflow</description>
        <step-plugin type='nixy-local-workflow-step'>
          <configuration>
            <entry key='script' value='echo "step two"' />
          </configuration>
        </step-plugin>
      </command>
      <command>
        <description>step three: node</description>
        <exec>echo "step three"</exec>
      </command>
    </sequence>
    <uuid>13ddd164-b981-4258-82b1-1b23c2cd8087</uuid>
  </job>
</joblist>
```

The nodes view output:
![image](https://user-images.githubusercontent.com/1311209/149640938-7c8085c3-98e7-4088-8464-f155780734aa.png)


And the log output:
![image](https://user-images.githubusercontent.com/1311209/149640942-505d7a16-f70c-4041-8d26-5f19b37848f6.png)

Tested in version 3.4.9 Enterprise.

**Comment by MegaDrive68k** [comment]
Thanks, @gaddman!

I see that happens with some steps.

With command steps it works:

<img width="1293" alt="Screen Shot 2022-01-18 at 18 35 18" src="https://user-images.githubusercontent.com/51376003/150022478-d12208f5-7604-4b9d-803a-c71db91cf6a5.png">

But using nixy steps:

<img width="1290" alt="Screen Shot 2022-01-18 at 18 34 46" src="https://user-images.githubusercontent.com/51376003/150022530-d0543472-3fd9-4b26-b85e-ebd9df9ce8fc.png">

**Comment by gaddman** [comment]
Just to be clear, it's not the nixy step at fault, it's the use of a workflow step that causes the problem. You'll see the same behaviour with any _workflow_ step AFAIK, eg the HTTP Request Step. Assuming this is a feature request, I'd like to see the workflow steps shown in the node view, preferably as an additional step in the node and marked as _Workflow_. but otherwise as an additional 'node' So either:

- node00
  - do a thing1
  - do a thing2
  - _Workflow step:_ do a thing3
  - do a thing4
- node01
  - do a thing1
  - do a thing2
  - _Workflow step:_ do a thing3
  - do a thing4

Or
- node00
  - do a thing1
  - do a thing2
  - do a thing4
- node01
  - do a thing1
  - do a thing2
  - do a thing4
- _Workflow_
  - do a thing3

The first approach works well when steps are run sequentially, maybe not so good if all steps are run in parallel.

**Comment by gaddman** [comment]
Pretty sure this is still present and would be useful to resolve.
