### ISSUE TITLE
Job search modal breaks UI outside jobs tab

### ISSUE THREAD

**Issue by ProTip** [rundeck/rundeck#7141]
**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
The job `Search` modal will not display if any tab other than "Jobs" is selected:

![image](https://user-images.githubusercontent.com/271965/123494500-a527ad00-d5e5-11eb-9b69-b3c4588461a6.png)

This will actually hang the UI due to the backdrop and the inability to dismiss the modal. This is being caused due to the modal residing in the Tab contents DOM hierarchy. Even though the modal has a position of `fixed` the inactive tab's display of `none` gets applied and it will not be visible.

**My Rundeck detail**
* Rundeck version: 3.4.0

**To Reproduce**
1. Go to jobs screen in a project
2. Click on `Graph`
3. Click on `Search` in the upper-right

**Expected behavior**
Modal should display or the search functionality should be hidden.

**Comment by whelme** [comment]
Now there are many opportunities to find a job not only in a great development company, but also to get help when moving to another country. I think that now [developer jobs with relocation assistance](https://relocate.me/search/software-developer) are especially relevant for many developers, because a lot of people are now relocating to other countries.
