### ISSUE TITLE
Unable to display big logs in node view

### ISSUE THREAD

**Issue by tazou** [rundeck/rundeck#7300]
**Describe the bug**

After migration from Rundeck v3.3.11.20210507-1 to v3.4.4.20210920 I've encountered the following bug: in a "Node" view, I'm no longer able to display the logs that exceed 6MB. Unlike the current version, in the v3.3.11 I was able to click the "expand" triangle icon to see the per-node log excerpt. 
Currently, all I have is a "whale log" notification which I was unable to override despite applying the following options:

rundeck.feature.legacyExecOutputViewer.enabled=true

**My Rundeck detail**

* Rundeck version: 3.4.4.20210920-1
* install type: deb
* OS Name/version: Debian 9.13
* DB Type/version: PostgreSQL v9.6

**To Reproduce**
1. Update rundeck to v3.4.4
2. Go on a job with a log size around 6MB or more
3. The log can't be displayed and we can see a whale.

**Expected behavior**

I would like to be able to see the "big log" in a "node view" or at least it's excerpt like in the v3.3.11.
I was in Rundeck v3.3.11.20210507-1 and I updated to v3.4.4.20210920-1 and I had a bug to display logs in "node" view when the logs are "big".

For example, if I have a log size of 6MB with the rundeck v3.3.11 I can click on the triangle icon to expand the node and see the log.
With the rundeck v3.4.4 I have a whale instead of the log.

I already have in my config file "rundeck-config.properties" this line : 
- rundeck.feature.legacyExecOutputViewer.enabled=true

But the problem is still here.

**Comment by tazou** [comment]
Hi @MegaDrive68k 
Thanks for your answer.
Do you know if an option exist to force to display "big logs" in node view ?
Because to debug a small problem in the "all log view" it's harder.

**Comment by virtual-expo** [comment]
Hello,

I would like to second @tazou on this one. In Rundeck v3.3.x I was able to read large logs. Event the logs exceeding 25MB would display flawlessly in the GUI node view.

Since Rundeck v3.4.x I'm unable to display complex logs exceeding 2MB. There is an option to display an excerpt:

```
rundeck.execution.logs.output.limit=2MB
rundeck.execution.logs.output.limitAction=truncate
```

However, this option is useless as long as it truncates the log at the beginning and not at the and of the file. This makes it impossible to check what went wrong midway the execution without downloading the whole log.

Could you please kindly advise if there is a way to display the whole log inside the GUI or at-least a way to truncate at the end (and not at the beginning) of the log?
