### ISSUE TITLE
[2.0.4] LDAP authentication does not support nested groups

### ISSUE THREAD

**Issue by dawud** [rundeck/rundeck#748]
``` 
Version     : 2.0.4                             Vendor: (none)
Release     : 1.15.GA                       Build Date: Sat 19 Apr 2014 01:29:46 AM CEST
```
When defining the `<security-role>` to a group whose members are other groups, as in this example taken from a `freeIPA` deployment:
```
# ipa group-show rundeck_users
  Group name: rundeck_users
  Description: Rundeck users
  GID: 1168000072
  Member groups: developers, operators
  Indirect Member users: john, jane, bob, lynn, george, matt
  Indirect Member groups: operators_1, operators_2, operators_3
```
authentication does not work, triggering the `HTTP ERROR 403 Problem accessing /rundeck/. Reason: !role` error.

Defining direct members into the group does work as expected.

**Comment by dpetzel** [comment]
I've run into this issue as well myself today on 2.4.0-1. In our case we are hitting Active Directory.  In case it makes a different I am looking to use nested groups for authentication as well as authorization. I have not tested the functionality for authorization, but for log on authentication it is not working.

Here is a sanitized version of my configuration:

```
activedirectory {
    org.eclipse.jetty.plus.jaas.spi.PropertyFileLoginModule sufficient
    debug="true"
    file="/etc/rundeck/realm.properties";
    com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
    contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
    providerUrl="ldap://my.dom:389"
    bindDn="CN=MINE"
    bindPassword="TOPSECRET"
    authenticationMethod="simple"
    forceBindingLogin="true"
    userBaseDn=MINE"
    userRdnAttribute="sAMAccountName"
    userIdAttribute="sAMAccountName"
    userPasswordAttribute="userPassword"
    userObjectClass="user"
    roleBaseDn="MINE"
    roleNameAttribute="cn"
    roleMemberAttribute="member"
    rolePrefix="rundeck."
    roleObjectClass="group"
    cacheDurationMillis="300000"
    reportStatistics="true"
    nestedGroups="true";
    };
```

I turned on `-Dcom.dtolabs.rundeck.jetty.jaas.LEVEL=DEBUG` and could see this line logged:
`JettyCachingLdapLoginModule:JettyCachingLdapLoginModule: User 'test_user' has roles:...`. The list of roles shown only included groups which the user was a direct member. It did not contain any of the nested groups, and the user received this error:

```
HTTP ERROR 403
Problem accessing /. Reason:
!role
Powered by Jetty://
```

I was able to sort of work around the issue by using the `supplementalRoles` configuration and setting that to the role defined in my web.xml. However this isn't really what we want to do since we don't want all users in the entire AD to be able to logon (even if it was just read-only). We really want to be able to limit logon to a single group and have that group contain subgroups.

Thanks

**Comment by knifhen** [comment]
I have submitted a pull-request to solve the issue where AD will not work with the nestedGroups feature

https://github.com/rundeck/rundeck/pull/1145

**Comment by gschueler** [comment]
@knifhen thank you!
