### ISSUE TITLE
No more logs since upgrading version

### ISSUE THREAD

**Issue by Nico4456** [rundeck/rundeck#7514]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
We were using, under docker, rundeck 3.2.1 without errors.
We upgraded to rundeck 3.4.6 by following the migration guide on the rundeck site.
Since then we have no more logs.
A problem with the switch to log4j2 with this new version of rundeck?
Can we please help as we can't find the problem?

I specify that for the rest, rundeck is functional, we found all the jobs at the end of the migration. Executions are operational. 

**Describe the bug**
No more logs since upgrading version

**My Rundeck detail**

* Rundeck version: 3.4.6
* install type: docker with rundeck's deb
* OS Name/version: debian 9.4 with docker
* DB Type/version: postgres

**To Reproduce**
Upgrade from 3.2.1 to 3.4.6

**Expected behavior**
log files supplied

**Comment by niall-munnelly** [comment]
If your problem is like the one I encountered, you'll see messages in your service log indicating that Rundeck couldn't create directory /server/logs - that is, in the server's root. 

The relevant line in your log4j2.properties file is here:

property.baseDir = ${sys:rundeck.server.logDir:-/server/logs}

Not knowing what the envvar should be called (RUNDECK_SERVER_LOGDIR?), I hard-coded it:

property.baseDir = ${sys:rundeck.server.logDir:-/opt/rundeck/server/logs}

...where the path to your logdir may differ.

That and a restart should get you sorted.
