### ISSUE TITLE
Syncing LDAP User Information Is Not Working (back on 4.0.0)

### ISSUE THREAD

**Issue by allenjeong** [rundeck/rundeck#7627]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
Enabling the LDAP sync feature (Active Directory) for a docker container via  these environment variables.
RUNDECK_JAAS_LDAP_USERFIRSTNAMEATTRIBUTE: givenName
RUNDECK_JAAS_LDAP_USERIDATTRIBUTE: sAMAccountName
RUNDECK_JAAS_LDAP_USERLASTNAMEATTRIBUTE: sn

**My Rundeck detail**
* Rundeck version: 4.0.0 (d344f689482d)
* install type: docker
* OS Name/version: Ubuntu 20.04
* DB Type/version: postgresql

**To Reproduce**

1. Perform an LDAP search and confirm the attributes are correct.
2. Set the appropriate environment variables.
3. Verify settings appear in files generated from templates.
4. Log in to Rundeck.
5. View user profile information and observe they are blank.

**Expected behavior**
Expect to see email address
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [MS edge]
 - Version [96.0.1054.34]

**Additional context**
This is the same issue with [RUN-315: Syncing LDAP User Information Is Not Working ](https://github.com/rundeck/rundeck/issues/7175)
which was solved on 3.4.10 and back on 4.0.0

**Comment by alexander-variacode** [comment]
I tried this issue and It happens randomly. However, I found this warning at Rundeck logs: 

`WARN  services.UserService - registerLogin: for john, caught OptimisticLockingFailureException: org.springframework.orm.hibernate5.HibernateOptimisticLockingFailureException: Object of class [rundeck.User] with identifier [1]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [rundeck.User#1]`

The walkaround I found was do logout and login again and the user data appears on Profile section:
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/80333592/163451393-377fdb02-aad9-476f-8cfe-c14ce60caea6.png">

**Comment by dingouerinitx** [comment]
Same Issue here, except for the fact that it happens with the local Login Module (`PropertyFileLoginModule`) instead of LDAP.

However I use LDAP as well and as a fallback the PropertyFileLoginModule with a local user **admin**.

To experiment with, I started to delete those entries (id 4,5) and tried to login again. It just created new double entries starting from ID 500+ (558,559) etc.

Strange thing, every time I delete the user manually and logging in again, **two rows** get added with almost the same values, but different ID! For me this seems odd, why should there be two rows for one logged in user???

You can verify this with

```bash
ssh <YOUR_RUNDECK_SERVER>
su postgres
psql
\c rundeck
\dt
DELETE FROM rduser WHERE id=X;
# log back in
select * from rduser;
```

Image before deletion

![image](https://user-images.githubusercontent.com/9012870/168835390-16ec47a9-4454-4e49-8dcc-0f96ef617997.png)

Image after deletion

![image](https://user-images.githubusercontent.com/9012870/168835171-74d3f855-351a-4247-aa0e-1b545433f224.png)

When editing the Profile manually, sometimes it works and after logout and login again the values for email, first_name, last_name remain, but after a while it disappears or gets removed by something. And sometimes it does not work at all...

Hopefully this helps a bit in narrowing it down...

Current Specs:

- Ubuntu 20.04
- Rundeck 4.2.1 (same behaviour at least since 3.4.0)
- Postgresql 14.2

The **jaas-ldap.conf** respectivelly **multiauth**:

*Do not credit me with the correctness of the properties of this config file for LDAP*

```conf
multiauth {

    com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule sufficient
      debug="true"
      contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
      providerUrl="ldap://XXX:389"
      bindDn="cn=XXXXX"
      bindPassword="XXXXXXXX"
      authenticationMethod="simple"
      forceBindingLogin="true"
      userBaseDn="ou=XXXXX"
      userRdnAttribute="sAMAccountName"
      userIdAttribute="sAMAccountName"
      userPasswordAttribute="userPassword"
      userObjectClass="person"
      userLastNameAttribute="sn"
      userFirstNameAttribute="displayName"
      userEmailAttribute="mail"
      roleBaseDn="ou=XXXXX"
      roleNameAttribute="roleName"
      roleMemberAttribute="memberOf"
      roleObjectClass="group"
      cacheDurationMillis="0"
      supplementalRoles="user,admin,architect,deploy,build"
      reportStatistics="true"
      timeoutRead="0"
      timeoutConnect="0"
      nestedGroups="false";

    org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
        debug="true"
        file="/etc/rundeck/realm.properties";
};
```

**Comment by FireHelmet** [comment]
Hi there, I also have the issue in the latest version, currently 4.4.0. Any update on this issue?

Thank you for the support!

**Comment by FireHelmet** [comment]
It works well in 4.4.0 in my case.

**Comment by nh4ttruong** [comment]
Rundeck 4.4.0 work well for syncing user profile:

Try to use **JettyCombinedLdapLoginModule** and config nearly same @dingouerinitx. Add to _jaas-loginmodule.conf_:
```
rundeck {
    com.dtolabs.rundeck.jetty.jaas.JettyCombinedLdapLoginModule sufficient
    ...
    ...
    ignoreRoles="false"
}
```
and _rundeck-config.properties_ :
```
rundeck.security.syncLdapUser=true
```

**Comment by allenjeong** [comment]
After upgrading Rundeck 4.4.0, it works after re-logging five times. But it works at once for my other colleague. Not sure if it is my AD problem or Rundeck, but let me close this ticket as it works anyway. 

Thanks for all you guys' confirmation.
