### ISSUE TITLE
Error loading http options after upgrade to 4.0

### ISSUE THREAD

**Issue by FedeHAL** [rundeck/rundeck#7638]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
After upgrading from 3.4.10 to 4.0.0 http options don't work if jobs.options.remoteUrlTimeout is present on rundeck.properties file

**My Rundeck detail**

* Rundeck version: 4.0.0
* install type: rpm
* OS Name/version: CentOS 8.4
* DB Type/version: postgresql

**To Reproduce**
1. Upgrade rundeck instance to 4.0
2. load up a form with http options on it.
3. Get server error.

**Screenshots**

<img width="674" alt="image" src="https://user-images.githubusercontent.com/66088961/162061925-e5a7292d-6090-4421-a90c-24b76f911f2e.png">

```
groovy.lang.MissingMethodException: No signature of method: rundeck.services.ConfigurationService.getInteger() is applicable for argument types: (String) values: [jobs.options.remoteUrlTimeout]
Possible solutions: getInteger(java.lang.String, java.lang.Integer)
```

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1
 - Browser Safari
 - Version 15.4

**Additional context**
If I comment the jobs.options.remoteUrlTimeout in my properties file it starts to work again.

**Comment by paulcalabro** [comment]
I see the following difference between 3.4.10 to 4.0.0 in _ScheduledExecutionService.groovy_, which I think is related:

```
git diff v3.4.10..v4.0.0
```

<img width="1372" alt="Screen Shot 2022-04-06 at 9 42 41 PM" src="https://user-images.githubusercontent.com/585059/162121694-0ff9af50-06de-49c1-bfc7-f67213e5768f.png">

I believe these are the corresponding definitions for the methods being called:

https://github.com/rundeck/rundeck/blob/81b9d2e2f9385c1fff5b7f17cd2f4132845e4b8d/rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy#L49-L51

https://github.com/rundeck/rundeck/blob/81b9d2e2f9385c1fff5b7f17cd2f4132845e4b8d/rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy#L68-L75

If I understand the issue correctly, it appears the second argument (_defval_) is missing.

Perhaps, the fix is as simple as adding a `null` value for the second arg like this:

https://github.com/rundeck/rundeck/blob/0875b68ce61cb3c8b89629b54e073ba36ef0b9a2/rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy#L239-L241
