### ISSUE TITLE
[SCM disabled] User don't have permissions to the configuration key.

### ISSUE THREAD

**Issue by mirkoknoll** [rundeck/rundeck#8218]
**Describe the bug**
Non-admin users don´t have permission to import jobs via SCM import plugin. Every time they go to jobs menu they see:
"[SCM disabled] User don't have permissions to the configuration key."
But the key has been created by the non-admin user itself in keys/project/my_project/my_github_token and the SCM import plugin has been configured by the user.

Access policy:

context:
  application: 'rundeck'
for:
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: [read]
  storage:
    - match:
        path: 'keys/.*'
      allow: '*' # allow all access to manage stored keys

**My Rundeck detail**

* Rundeck version: 4.11.0
* install type: war
* OS Name/version: Debian 11
* DB Type/version: mysql

**To Reproduce**
1. Go to 'Project Settings -> Setup SCM' as non-admin user
2. Click on 'Git Import -> Enable'
3. Go back to 'Jobs'
4. See error in red "[SCM disabled] User don't have permissions to the configuration key. Please refer to the system's SCM key owner or administrator for further actions."

**Expected behavior**
See blue "Import needed" above "Jobs actions" menu.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome, edge]
 - Version [latest (111)]

**Additional context**

**Comment by stusoper** [comment]
I was also seeing this behaviour in Enterprise Version 4.10.0. I upgraded the cluster to 4.12.0 and the issue is still present.
I have a shared key for SCM based in keys/ (not project specific as it's used across all projects) where a non-admin user has been granted read access to be able to perform an SCM import or SCM export.
When the user goes to the Jobs page after SCM import has been configured and enabled, the following message is displayed:
[SCM disabled] User don't have permissions to the configuration key. Please refer to the system's SCM key owner or administrator for further actions.

Once a user receives this message, SCM import is disabled in that project for all users and requires re-enabling by an admin.
Before re-enabling SCM import, if the Jobs page is visited again, the message is no longer present and an SCM export can still take place if any changes have been made to any jobs.
The interesting thing here is the same key is being referenced for SCM export and SCM import but the issue only arises when SCM import is enabled.

**Comment by mirkoknoll** [comment]
Works again with 4.14.0
