### ISSUE TITLE
Incomplete certificates chain for packages.rundeck.com

### ISSUE THREAD

**Issue by lroehrs** [rundeck/rundeck#8250]
**Describe the bug**
We're installing Rundeck with deb/apt and got since yesterday the following failure:

```
curl -L https://packages.rundeck.com/pagerduty/rundeckpro/gpgkey
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

The reason is an incomplete certificates chain:

```
openssl s_client -connect packages.rundeck.com:443 -servername packages.rundeck.com -verify 5
...
Verification error: unable to verify the first certificate
...
```

You can also check it here:
https://www.ssllabs.com/ssltest/analyze.html?d=packages.rundeck.com&s=75.2.53.26

I guess the certificate was shortly changed:
```
        Validity
            Not Before: Apr 12 00:00:00 2023 GMT
            Not After : Apr 17 23:59:59 2024 GMT
```

Please note: On MacOS, cURL is autocomplete (or something like that) the certificates chain. 

**My Rundeck detail**

* install type: deb
* OS Name/version: ubuntu 18.04, 20.04, 22.04

**Comment by TibbeVandenBerghe** [comment]
`sudo wget http://cacerts.digicert.com/DigiCertGlobalG2TLSRSASHA2562020CA1-1.crt.pem -O /home/ubuntu/cabundle.crt`

`sudo cp /home/ubuntu/cabundle.crt /usr/local/share/ca-certificates/`

`sudo update-ca-certificates`

Is a fix for Debian. This installs the missing intermediate certificate
Disclaimer: tested with a curl for `sudo curl -L --cacert /home/ubuntu/cabundle.crt https://packages.rundeck.com/pagerduty/rundeck/gpgkey `

**Comment by niko2** [comment]
@TibbeVandenBerghe this is not a fix but a workaround...

The SSL chain remains incomplete and needs to be fixed. Hope it will be handled with this issue :crossed_fingers:

**Comment by nethsix** [comment]
Thank you @lroehrs for reporting the issue, and identifying the root cause (SSL cert renewal)!
Thank you @TibbeVandenBerghe for finding a workaround so quickly and sharing details!
Thank you @niko2 for pointing out that the chain needs to be fixed!
Thank you @tanjinP for pointing/emphasizing to @TibbeVandenBerghe 's workaround while we investigate.

The certifcate chain seems to be unrecognized (deemed broken) by some OS versions, while it worked for others. After renewing the SSL cert, I tested installing packagecloud.io/pagerduty/rundeck and packagecloud.io/pagerduty/rundeckpro packages on ubuntu/jammy, fedora/36 and both worked. It seemed that from @TibbeVandenBerghe that running `openssl s_client -connect packages.rundeck.com:443 -servername packages.rundeck.com -verify 5` may fail though.

We installed the certificate chain given to use by the certifcate provider but it may be 'imperfect' leading to this certificate chain broken issue for some OS versions. @TibbeVandenBerghe 's workaround helped us to dig deeper. In the end we used, Certifcate Composer (more accurately certificate chain composer) https://tools.keycdn.com/certificate-chain to generate the chain, and this has likely fixed the issue.

We reconfirmed with the same SSL tool @TibbeVandenBerghe used https://www.ssllabs.com/ssltest/analyze.html?d=packages.rundeck.com.

Please do let us know if anyone is still having issues.

**Comment by lroehrs** [comment]
@nethsix It's now fixed, thank you!

**Comment by nethsix** [comment]
@lroehrs Thanks for confirming so promptly 🙇
