### ISSUE TITLE
Feature request: add a "failover" node type

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#874]
Hello,
I am using Rundeck to launch jobs on several servers.
Some of these servers are unique and each of them is registered as a node.

But I also have "redundant" servers; so I would like to be able to have both of them as target nodes in my job; but I would like the job to execute on only 1 node.

Example:

My job "testjob" has 2 servers as target nodes: server1 & server2

If server1 is down, "testjob" will detect server1 as down and will try to execute on server2. (if testjob is configured up for that)

The problem is: if server1 is up, "testjob" will execute on it but it will also execute on server2.
So testjob will execute 2 times on both members of my cluster (server1 and server2); which is useless. 1 execution on server1 or server2 is sufficient.

Maybe is it possible to have an attribute on nodes which tells to the job: "these nodes are redundant; no need to execute jobs on both of them" ?

I know there are other ways to do that, without affecting Rundeck (F5 VIP, virtual servers, clustered nodes setup,...) but for several reasons; in that case; I can't do that.

Thanks for your help.

Best regards.
Jérôme

**Comment by gschueler** [comment]
Enterprise Node Healthcheck plus a custom Node orchestrator plugin would be a solution: the job targets both nodes, which each have a priority attribute; Node healthcheck will prefilter the nodes for the job to only healthy nodes when executed; the Node Orchestrator can select only one node, ordered by priority, so that in the case both nodes are healthy only the highest priority node is executed on.

**Comment by sgrimm** [comment]
In case anyone comes here searching for a way to do this: It is a bit of an ugly hack and native failover support would be better, but we solved this using Consul's DNS interface since we were using Consul for service discovery already anyway.

We register a Consul health check for the ssh service on each host, and include a tag that identifies a cluster of hosts that can run in a failover configuration. For example, say we have hosts reporting-1 and reporting-2 and reporting-3 that have identical ability to run Rundeck jobs: they would all have a tag of `reporting` in Consul.

Then we can add `reporting.ssh.service.consul` to the Rundeck node list. Rundeck thinks it is connecting to a host by that name, but when it does its DNS lookup, Consul returns the address of a host with the `reporting` tag whose ssh service is healthy. Thus when a host goes down, the jobs fail over automatically and Rundeck is none the wiser; it just gets back a different IP address when it looks up the hostname.

Obviously this requires that `.consul` DNS lookups go to the Consul agent, but if you're using Consul for service discovery you probably already have that in place for use by other things. (If you don't: dnsmasq is a good way to do it.)

This isn't a perfect solution but maybe someone else will find it applicable to their situation too.
