### ISSUE TITLE
Quotes vanish when using "Command" workflow step

### ISSUE THREAD

**Issue by molinarif02** [rundeck/rundeck#8780]
**Description of the bug**
When running this command as a workflow step:
`powershell.exe -File "D:\Path\To\Script\File.ps1" ${option.argument1} ${option.argument2}`
the quotes around the option vanish, and as `argument2` is a string which contains spaces, it behaves as if it was multiple arguments.

I've already tried "manually" adding both double (") and single (') quotes and using them with the `${unquotedoption.argument*}` but I still experience the same isssue.

**My Rundeck details**
* Rundeck version: [v5.0.0-20231216]
* install type: [rpm]
* OS Name/version: [RHEL 9.3]
* DB Type/version: [postgres]

**Comment by radiowavesurfer** [comment]
Since upgrading I'm also seeing the same sort of problems on existing workflows which have previously worked fine.

In my case I'm using the key-value log handler to capture JSON data from workflow steps, and then in a later step passing the values back in as command arguments to a number of python scripts. (The key-value handler is using entirely the default settings.)

So the command would look something like: `myscript.py --data ${data.id}`

I've modified the python scripts to begin by printing their args (i.e. `print(sys.argv)`), and so when looking at the rundeck page of a failed execution, I can see the data value both as it was received by rundeck in the "KEY VALUE DATA: RESULTS" panel, _and_ as it was later received by the python script as a command argument.

Here are specific examples of the two type of discrepancies I've seen:

Key-value data: `["SO-0014848"]`
Python arg: `'[SO-0014848]'`
(The value python has received is missing the double-quotes inside the square brackets.)

Key-value data: `[108094, 108095]`
Python arg: `'[108094,', '108095]'`
(Whereas the key-value data is a single string, it's been passed to python as two separate args.)

I'm currently working around this issue by converting these commands into inline scripts.
Thanks.

**My Rundeck detail**

* Rundeck version: Rundeck5.0.02023-12-16
* install type: deb
* OS Name/version: ubuntu 20.04
* DB Type/version: postgres 12

**Comment by mazzella-c** [comment]
Same issue as #8773 I presume.

**Comment by MegaDrive68k** [comment]
The issue https://github.com/rundeck/rundeck/issues/8773 has been reproduced, let's follow the problem there. 

Thanks for your feedback  @molinarif02  @radiowavesurfer @mazzella-c!
