### ISSUE TITLE
output of python shows up only at the end of the execution

### ISSUE THREAD

**Issue by maxadamo** [rundeck/rundeck#885]
print statements in a python script are not showing up  synchronously (when they are run from the script) but they show up together when the script ends its execution. 
I could try to replace "print" with "sys.stdout.write", but it makes no sense, as all python script use print statement.

**Comment by hs-hub-world** [comment]
Hi, sorry for replying to an old post but it seems this problem still exists. Can you please answer these questions?
 - in order to use the unbuffered mode, did you have to upgrade python to version> 3.x 

 - by upgrading python to version 3.x that means the py-winrm-plugin script "winrm-exec.py" will not work because the syntax is not python ver 3.x compatible, right -?

- So, did you have to update the winrm-exec.py script syntax -?

- in my case I did upgrade the winrm-exec.py script syntax (i.e. adding parenthesis for each print statement Print ("xxx") required by version 3.x), are there other updates we had to do -?

- and looks like Rundeck version 2.11.3-1 does pass command "-u" line switch but even then the output is not immediately returned back to the console while it’s running.

Can you please provide the steps you have taken to resolve this issue? I am sure others are having the same issue; this will greatly help the larger community.

Thank you!

**Comment by maxadamo** [comment]
@hs-hub-world as far as I remember:
- on 2014 I was not using python 3. Most probably it was python 2.6 (the one running on CentOS 6) 
- All you need is `python -u` at the beginning of your script: 
#!/usr/bin/python -u

**Comment by maxadamo** [comment]
@hs-hub-world speaking about example 2, what you're reporting, consist of *ONE* python statement:
```
winrm.Session('YOURHOSTSERVER', auth=('WINUSER','WINPASS'),transport='ntlm').run_ps("whoami;sleep 5;pwd").std_out
```
in other words, the end of the script is also the end of the statement and it's normal to see the output of the end. 

Example 1: similarly to problem 2, you are running 1 statement. In my opinion, you need to change the interpreter inside `winrm-exec.py`. The first line should look like:
`#!/usr/bin/python -u`

**Comment by hs-hub-world** [comment]
@maxadamo, 
    do you use Rundeck -? If yes, do you use "WinRM Node Executor Python" module -? If Yes, when you execute WinRm command under Log Output do you see the winrm results immedately while it's still running.  If yes, if you don't mind can you please paste some screenshots.
by the way, I have tried your suggestion and that still does not work. It seems to me everyone should be experiancing the same issue here...  

Here are my results:
![winrm-python-screenshot-1](https://user-images.githubusercontent.com/20629911/40316626-c56b2486-5cd3-11e8-9f81-e625dc328d5a.PNG)

**Comment by bran2k7** [comment]
Just want to add my 2 cents with this issue. Using the built-in script file plugin, when executing a python script, print statements are buffered. #!/usr/bin/python3 -u does work but only on certain systems. others would require something like #!/usr/bin/env python3 -u which doesn't work. I would think rundeck wouldn't buffer by default.

**Comment by sbilello** [comment]
you can try with 
```
export SHELL=/bin/bash
export TERMINFO=/usr/lib/terminfo
export TERM=xterm-256color
/usr/local/python3 -u <yourpythonscript>
```
