### ISSUE TITLE
Feature Request: GUI for ACL Policy

### ISSUE THREAD

**Issue by gentunian** [rundeck/rundeck#941]
It turns out that I spent a lot of time trying to configure the `<user>.aclpolicy` file. Unfortunately, changes won't take effect without a restart (despite that the doc says the contrary).

It would be also great that project admins could also deliver and provide authorization to the project jobs, in order to have a full self-service tool.

**Comment by foundatron** [comment]
+1 . I've been struggling to set up ACL policies the past week for Rundeck. I find current process of of add user/dev to relam.propeties, restart rundeck, create aclpolicy to be unintuitive. A GUI would help a lot. I think a place to start would be something similiar to Jenkin's Project-based Matrix Authorization Strategy. It's basically a grid with users and groups on one axis, permissions on the the other. This combined with some standard roles to select from that then can be customized would be awesome.

**Comment by wricardo** [comment]
:+1:

**Comment by PeterGarlic** [comment]
Now we are near to 2 years from the initial request. While rd-acl is a nice tools a simple acl GUI would be a great improvement!.
Unfortunately I´not java and/or groovy programmer....

**Comment by aes512** [comment]
+1 - our company refuses to use RunDeck due to the complexities surrounding the ACL editing and management shortcomings.

**Comment by xeor** [comment]
Anything? We are almost in the same boat. Not very userfriendly :(

I guess we got http://rundeck.org/docs/man1/rd-acl.html. But that won't cut it in most cases

**Comment by jszaszvari** [comment]
I think the reason that this has been open for so long is because someone would actually have to understand how the ACL's work in RunDeck in quite a bit of depth to be able to write a WebUI that can generate them reliably. 

And thats the issue, I'm not sure any-more if there is even 1 person, working for them or in the world that understands them properly or in depth.

Everyone relies on configs that have been passed around that someone got working, but cant tell you how/just guessed it and got lucky.

Took me 7 months before I could log in with a AD user

**Comment by gschueler** [comment]
Thanks for the comments about this issue, it really hits home that the ACL system is complex, and lacking a GUI makes it frustrating and hard to use.  :( A "feature" is not a feature if it is difficult or onerous to actually use it! `rd-acl` was an attempt to alleviate this somewhat, but obviously it's not sufficient. The ACL system became complex because it needed to be granular and flexible, but that is certainly a stumbling block to using Rundeck effectively.  

I created a Trello card here for votes on this issue: https://trello.com/c/5udyWrNA
