### ISSUE TITLE
make threadcount configurable through options

### ISSUE THREAD

**Issue by michaelgibson** [rundeck/rundeck#942]
It would be nice to be able to specify the number of threads for a job at execution time.
Additionally it would be nice if the threadcount setting would be able to get that value from a ${options.threadcount} variable.

**Comment by shawnchasse** [comment]
Adding my 2 cents in on this one. It would be nice to set 2 variables for threadcount:
1. max thread count - so that the maximum number of threads is capped at some predetermined value
2. default thread count - the default thread count = or < max thread count so that the most used option would be set without the user having to change anything. 

We run into threadcount issues a lot and since we utilize one job for many 'services' it would be nice to have a more dynamic thread count configuration since service A can handle X threads but service B can only handle Y threads.

**Comment by ahonor** [comment]
The thread count can be specified via an option variable.
