### ISSUE TITLE
Number of nodes wrong on "Run Again" in 2.2.1, even more wrong in 2.2.3!

### ISSUE THREAD

**Issue by richiereynolds** [rundeck/rundeck#991]
Hi, I recently upgraded from v2.2.1 with the built in DB to v2.2.3 with mysql.

In v2.2.1 if I select "Run Again" on an execution that was run against a single node, the nodes section says:
Nodes Change the Target Nodes (2)
When I expand the nodes I can see there is only 1 selected, yet it confusingly says 2.

In v2.2.3 if I select "Run Again" on an execution that was run against a single node, the nodes section says:
Nodes Change the Target Nodes (3)
When I expand the nodes I can see there is only 1 selected, yet it confusingly says 3!!

This is disconcerting for the user and means you have to expand all the nodes to be certain what you're actually running against.

I really like rundeck and am currently trying to convince teams in my company to move to using it but seemingly small issues like this really aren't helping my case!

In a similar vein, when you execute a job, all nodes are selected by default.
It is simply too big a risk to allow this to be used in production in many cases e.g. an admin deploys the wrong software to the wrong boxes as he forgot to deselect the nodes.
We desperately need an option to have all nodes unselected by default and the UI to give an accurate representation of what rundeck will do.
If that doesn't hapen reasonably quickly I fear we'll end up moving to another tool :(

P.S. Primarily using chrome & firefox, RHEL 6.5 linux as the server, RPM install.

Thanks, Richard.

**Comment by gschueler** [comment]
can you describe the type of job workflow that you are running?

**Comment by gschueler** [comment]
also, what OS, browser, browser version? thanks.

**Comment by richiereynolds** [comment]
windows 7 and chrome Version 40.0.2214.91 m
rundeck server is running on linux rh 6.5
it's a node based job where the user can select a number of nodes

**Comment by gschueler** [comment]
i'm wondering if you have job reference steps, and whether they might be node steps or workflow steps

**Comment by richiereynolds** [comment]
Yes, the job refs other jobs, some of which are workflow and some of which are node steps.

Sent from my BlackBerry® wireless device

-----Original Message-----

**Comment by gschueler** [comment]
thanks, I was able to reproduce this.

the problem is that rundeck was using the list of failed + list of successful nodes as the "selected set".  This differs from the original node set when workflow step job references are used, since they automatically act as if they are on the localhost (server) node.  As well, if you have job references which execute on different nodes than the original set, those would be included in the selected set when you retry.

the fix is to make use of the actual selected set from the original execution when showing the selected nodes for the attempted retry.
